import {decodeMessage,noteName,controlStats,pitchStats,clockStats,classifyEncoder,messageRate,peakMessageRate,velocityStats,latencyStats,analyzeNotePairs,compareLoopback,detectFloods,analyzeCcPairs,createParameterTracker,processParameterMessage,baselineDiff,chordName,channelStats,performanceStats,reportSummary,switchStats,rollingBpm,validateReport,isSwitchLike} from './midi-core.js';
import {buildTestResults,STATUS_LABEL,TEST_GUIDE,TEST_TERMS} from './midi-tests.js';
const STATUS_ICON={notrun:'○',info:'ℹ',ok:'✓',attention:'!',investigate:'⚠'};
import {analyzeWindowsScan,analyzeLogText} from './midi-winlog.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
const ids=['connect','helpBtn','midiStatus','input','output','preset','enableSysex','pause','clear','elapsed','support','summary','findings','inventory','guided','guidedTitle','guidedText','guidedBack','guidedSkip','guidedNext','monitor','search','deviceFilter','channelFilter','typeFilter','displayMode','autoscroll','clearLog','exportCaptureCsv','exportCaptureJson','messageStats','channels','controls','controlTitle','controlDetail','controlGraph','controlHistogram','isolateControl','pedalStats','aftertouchStats','hiresStats','expectedLow','expectedHigh','expectedCount','applyExpected','keyboard','keySummary','held','notePairStats','velocityStats','velocityHistogram','perKeyVelocity','clock','performanceStats','floods','runLoopback','loopbackStats','latencyStats','latencyHistogram','outChannel','outNote','outVelocity','noteOn','noteOff','outCc','outCcValue','sendCc','outProgram','sendProgram','outPitch','sendPitch','panicChannel','panicAll','connections','learn','copyLearn','mappingLabel','addMapping','mappingRows','exportMappingCsv','exportMappingJson','printMapping','saveBaseline','importReport','compareBaseline','clearLocal','exportReport','exportReportCsv','printReport','reportHuman','reportPreview','helpDialog','guidedEnd','sysexStats','pitchStats','pitchRange','pitchNow','mpeStats','clockHistogram','loopRounds','polyExpected','burstCount','runBurst','burstStatus','testResults','winDays','winScan','winCopyScript','winImport','winStatus','winResults'];
const els=Object.fromEntries(ids.map(id=>[id,$('#'+id)]));

const ingestHooks=[],reportExtensions=[];let bulk=false;
const portStates=new Map(),lastDisconnectByName=new Map();
let lastRender=0,renderTimer=null;
let access=null,currentInput=null,currentOutput=null,lastDecoded=null,sysexEnabled=false,selectedControl=null,paused=false,renderQueued=false;
const paramTracker=createParameterTracker();
const guidedSteps=[
 ['Connection','Enable MIDI and select the controller input you want to diagnose.'],
 ['Key sweep','Press every key or pad once. Set an expected key range in Keyboard if you know it.'],
 ['Velocity','Play notes softly and hard, then repeat one key at similar force.'],
 ['Controls','Move every knob and slider through complete travel, then leave each stationary briefly.'],
 ['Pitch bend','Move pitch bend fully both directions and release to center several times.'],
 ['Mod / expression','Sweep modulation, expression and other continuous controls.'],
 ['Buttons','Press each button or switch at least once.'],
 ['Pedals','Operate sustain and any expression/foot controls through normal travel.'],
 ['Aftertouch','If supported, test channel or polyphonic pressure.'],
 ['Timing / loopback','Optional: inspect timing or route MIDI OUT back to MIDI IN and run loopback.'],
 ['Review','Review findings, label mappings, save a baseline and export the report.']
];
const state={device:'',started:Date.now(),events:[],timestamps:[],keys:new Set(),held:new Set(),channels:new Set(),messageCounts:{},cc:new Map(),ccTimes:new Map(),pitchValues:[],pitchTimes:[],pitchByChannel:new Map(),clockTimes:[],connections:[],disconnects:0,reconnects:0,mappings:[],velocityValues:[],velocityByKey:new Map(),sustainValues:[],sustainTimes:[],guidedSkipped:[],guidedEnded:false,aftertouch:[],polyAftertouch:new Map(),programs:[],transport:[],songPosition:null,paramEvents:[],hires:[],sysex:[],mpe:new Map(),expected:{low:null,high:null,count:null},guided:false,guidedStep:0,peakRate:0,loopback:null,latencies:[],importedReport:null,burst:null,winScan:null,winAnalysis:null,logAnalyses:[],testWindowStart:Date.now()};

function resetState(keepMappings=true){
 const mappings=keepMappings?state.mappings:[];
 Object.assign(state,{device:currentInput?.name||'',started:Date.now(),events:[],timestamps:[],keys:new Set(),held:new Set(),channels:new Set(),messageCounts:{},cc:new Map(),ccTimes:new Map(),pitchValues:[],pitchTimes:[],pitchByChannel:new Map(),clockTimes:[],connections:[],disconnects:0,reconnects:0,mappings,velocityValues:[],velocityByKey:new Map(),sustainValues:[],sustainTimes:[],guidedSkipped:[],guidedEnded:false,aftertouch:[],polyAftertouch:new Map(),programs:[],transport:[],songPosition:null,paramEvents:[],hires:[],sysex:[],mpe:new Map(),peakRate:0,loopback:null,latencies:[],importedReport:null,burst:null,testWindowStart:Date.now()});
 lastDecoded=null;selectedControl=null;paramTracker.channels.clear();els.monitor.innerHTML='';els.connections.textContent='';renderAll(true);renderMappings();
}
function logConnection(text){const line=new Date().toLocaleTimeString()+'  '+text;state.connections.unshift(line);state.connections=state.connections.slice(0,100);els.connections.textContent=state.connections.join('\n')}
function setStatus(text,kind=''){els.midiStatus.textContent=text;els.midiStatus.className='status-pill '+kind;els.support.textContent=text}
function portName(p){return p?.name||p?.manufacturer||p?.id||'Unknown MIDI port'}
function fillPorts(){
 if(!access)return;const oldIn=els.input.value,oldOut=els.output.value,ins=[...access.inputs.values()],outs=[...access.outputs.values()];
 els.input.innerHTML='<option value="">No input selected</option>'+ins.map(p=>'<option value="'+esc(p.id)+'">'+esc(portName(p))+'</option>').join('');
 els.output.innerHTML='<option value="">No output selected</option>'+outs.map(p=>'<option value="'+esc(p.id)+'">'+esc(portName(p))+'</option>').join('');
 els.deviceFilter.innerHTML='<option value="">All devices</option>'+ins.map(p=>'<option value="'+esc(p.id)+'">'+esc(portName(p))+'</option>').join('');
 if(access.inputs.has(oldIn))els.input.value=oldIn;else if(ins.length===1)els.input.value=ins[0].id;
 if(access.outputs.has(oldOut))els.output.value=oldOut;else if(outs.length===1)els.output.value=outs[0].id;
 bindInput();if((access.outputs.get(els.output.value)||null)!==currentOutput)bindOutput();else updateHardwareControls();
}
function bindInput(){const next=access?.inputs.get(els.input.value)||null;if(next===currentInput&&next?.onmidimessage===onMidi)return updateHardwareControls();if(currentInput)currentInput.onmidimessage=null;currentInput=next;if(currentInput){currentInput.onmidimessage=onMidi;state.device=portName(currentInput);logConnection('Input selected: '+state.device);setStatus('Listening: '+state.device,'connected')}updateHardwareControls()}
function bindOutput(){currentOutput=access?.outputs.get(els.output.value)||null;if(currentOutput)logConnection('Output selected: '+portName(currentOutput));updateHardwareControls()}
const outputControls=['noteOn','noteOff','sendCc','sendProgram','sendPitch','panicChannel','panicAll','runLoopback','runBurst'];
function updateHardwareControls(){for(const id of outputControls){els[id].disabled=!currentOutput;els[id].title=currentOutput?'':'Enable MIDI and select an output first.'}els.runLoopback.disabled=!currentOutput||!currentInput;els.runBurst.disabled=!currentOutput||!currentInput||!!state.burst?.active}
async function requestMidi(sysex=false){
 if(!navigator.requestMIDIAccess){setStatus('Web MIDI is unavailable. Use a current Chromium-based browser on HTTPS.','attention');return}
 try{access=await navigator.requestMIDIAccess({sysex});sysexEnabled=sysex;for(const p of [...access.inputs.values(),...access.outputs.values()])portStates.set(p.id,p.state);access.onstatechange=onPortState;fillPorts();els.connect.disabled=true;els.connect.textContent='MIDI enabled';els.enableSysex.textContent=sysex?'SysEx enabled':'Enable SysEx';setStatus((sysex?'MIDI + SysEx enabled':'MIDI enabled')+(currentInput?' · Listening: '+state.device:' · select an input'),'connected')}catch(e){setStatus((e?.name==='NotAllowedError'||e?.name==='SecurityError'?'MIDI permission not granted: ':'MIDI could not start ('+(e?.name||'error')+'): ')+(e?.message||e)+' You can retry Enable MIDI.','attention')}
}
function onPortState(e){const p=e.port,prev=portStates.get(p.id);portStates.set(p.id,p.state);if(prev!==p.state){logConnection(p.type+' '+portName(p)+': '+p.state+'/'+p.connection);const name=portName(p),now=performance.now();if(p.state==='disconnected'&&prev==='connected'){const last=lastDisconnectByName.get(name);if(last===undefined||now-last>1000){state.disconnects++;maybeAutoScan('a MIDI disconnect')}lastDisconnectByName.set(name,now)}if(p.state==='connected'&&prev==='disconnected'&&p.type==='input')state.reconnects++}fillPorts();scheduleRender()}
function onMidi(ev){
 const t=ev.replayT??performance.now(),d=decodeMessage(ev.data),deviceId=ev.currentTarget?.id||currentInput?.id||'',device=portName(ev.currentTarget||currentInput),e={...d,t,wallTime:new Date().toISOString(),deviceId,device};lastDecoded=e;for(const h of ingestHooks)h(e);
 if(matchLoopback(e)||matchBurst(e))e.loopback=true;state.events.push(e);if(state.events.length>5000)state.events.shift();state.timestamps.push(t);if(state.timestamps.length>5000)state.timestamps.shift();state.peakRate=Math.max(state.peakRate,peakMessageRate(state.timestamps));state.messageCounts[d.kind]=(state.messageCounts[d.kind]||0)+1;if(e.loopback){if(!paused&&!bulk&&matchesMonitor(e))appendMonitorRow(e);scheduleRender();return}if(d.channel)state.channels.add(d.channel);
 if(d.kind==='noteon'){state.keys.add(d.a);state.held.add(d.a);state.velocityValues.push(d.b);if(!state.velocityByKey.has(d.a))state.velocityByKey.set(d.a,[]);state.velocityByKey.get(d.a).push(d.b);if(state.velocityValues.length>2000)state.velocityValues.shift();if(state.velocityByKey.get(d.a).length>200)state.velocityByKey.get(d.a).shift();state.mpe.set(d.channel,{note:d.a,pitch:state.mpe.get(d.channel)?.pitch||0,pressure:0,timbre:state.mpe.get(d.channel)?.timbre||0})}
 if(d.kind==='noteoff'){state.held.delete(d.a);if(state.mpe.get(d.channel)?.note===d.a)state.mpe.delete(d.channel)}
 if(d.kind==='cc'){const k=d.channel+':'+d.a;if(!state.cc.has(k))state.cc.set(k,[]);if(!state.ccTimes.has(k))state.ccTimes.set(k,[]);state.cc.get(k).push(d.value);state.ccTimes.get(k).push(t);if(state.cc.get(k).length>1000)state.cc.get(k).shift();if(state.ccTimes.get(k).length>1000)state.ccTimes.get(k).shift();if(d.a===64){state.sustainValues.push(d.value);state.sustainTimes.push(t);if(state.sustainValues.length>1000){state.sustainValues.shift();state.sustainTimes.shift()}}if(d.a===74&&state.mpe.has(d.channel))state.mpe.get(d.channel).timbre=d.value;const pe=processParameterMessage(paramTracker,d);if(pe){state.paramEvents.push({...pe,t});if(state.paramEvents.length>200)state.paramEvents.shift()}state.hires=analyzeCcPairs(state.events.slice(-500))}
 if(d.kind==='pitchbend'){if(!state.pitchByChannel.has(d.channel))state.pitchByChannel.set(d.channel,{values:[],times:[]});const pc=state.pitchByChannel.get(d.channel);pc.values.push(d.value);pc.times.push(t);if(pc.values.length>1000){pc.values.shift();pc.times.shift()}state.pitchValues.push(d.value);state.pitchTimes.push(t);if(state.pitchValues.length>1000)state.pitchValues.shift();if(state.pitchTimes.length>1000)state.pitchTimes.shift();if(state.mpe.has(d.channel))state.mpe.get(d.channel).pitch=d.value}
 if(d.kind==='clock'){state.clockTimes.push(t);if(state.clockTimes.length>1000)state.clockTimes.shift()}
 if(['start','continue','stop'].includes(d.kind)){state.transport.push({kind:d.kind,t});if(state.transport.length>100)state.transport.shift()}
 if(d.kind==='songposition')state.songPosition=d.value;
 if(d.kind==='aftertouch'){state.aftertouch.push(d.value);if(state.aftertouch.length>1000)state.aftertouch.shift();if(state.mpe.has(d.channel))state.mpe.get(d.channel).pressure=d.value}
 if(d.kind==='polyaftertouch'){const k=d.channel+':'+d.a;if(!state.polyAftertouch.has(k))state.polyAftertouch.set(k,[]);state.polyAftertouch.get(k).push(d.value);if(state.polyAftertouch.get(k).length>300)state.polyAftertouch.get(k).shift()}
 if(d.kind==='program'){state.programs.push({channel:d.channel,value:d.value,t});if(state.programs.length>500)state.programs.shift()}
 if(d.kind==='sysex'){state.sysex.push({t,length:d.raw.length,hex:d.hex,manufacturer:d.raw[1]??null});if(state.sysex.length>200)state.sysex.shift()}
 if(!paused&&!bulk&&matchesMonitor(e))appendMonitorRow(e);scheduleRender();
}
function matchesMonitor(e){const q=els.search.value.trim().toLowerCase(),df=els.deviceFilter.value,ch=els.channelFilter.value,ty=els.typeFilter.value;if(df&&e.deviceId!==df)return false;if(ch&&String(e.channel)!==ch)return false;if(ty&&e.kind!==ty)return false;return !q||JSON.stringify([e.device,e.label,e.kind,e.value,e.decimal,e.hex,e.channel,e.a]).toLowerCase().includes(q)}
function rowHtml(e){const mode=els.displayMode.value,decoded=mode!=='raw',raw=mode!=='decodedOnly';return '<td>'+(e.t/1000).toFixed(3)+'</td><td>'+esc(e.device)+'</td><td>'+(e.channel??'—')+'</td><td>'+(decoded?esc(e.kind):'—')+'</td><td>'+(decoded?esc(e.label):'—')+'</td><td>'+(decoded?esc(e.value):'—')+'</td><td class="muted-cell">'+(raw?esc(e.decimal):'—')+'</td><td class="muted-cell">'+(raw?esc(e.hex):'—')+'</td>'}
function appendMonitorRow(e){const tr=document.createElement('tr');tr.innerHTML=rowHtml(e);els.monitor.append(tr);while(els.monitor.children.length>600)els.monitor.firstChild.remove();if(els.autoscroll.checked)els.monitor.parentElement.scrollTop=els.monitor.parentElement.scrollHeight}
function rebuildMonitor(){els.monitor.innerHTML='';for(const e of state.events.slice(-600).filter(matchesMonitor))appendMonitorRow(e)}
// Throttle rendering so high-rate streams cannot starve the UI; only the visible view is re-rendered.
const RENDER_INTERVAL_MS=120;
function scheduleRender(){if(renderQueued)return;renderQueued=true;const wait=Math.max(0,RENDER_INTERVAL_MS-(performance.now()-lastRender));renderTimer=setTimeout(()=>requestAnimationFrame(()=>{renderQueued=false;lastRender=performance.now();renderAll(false)}),wait)}
function stat(label,value){return '<div class="stat"><strong>'+esc(value)+'</strong><span>'+esc(label)+'</span></div>'}
function metric(label,value){return '<div class="metric"><strong>'+esc(value)+'</strong><span>'+esc(label)+'</span></div>'}
function histogram(el,bins=[]){const max=Math.max(1,...bins);el.innerHTML=bins.map((v,i)=>'<span style="height:'+Math.max(3,v/max*100)+'%" title="Bin '+(i+1)+': '+v+'"></span>').join('')}
function meterRows(entries){const max=Math.max(1,...entries.map(x=>x[1]));return entries.map(([k,v])=>'<div class="meter-row"><span>'+esc(k)+'</span><div class="meter-track"><div class="meter-fill" style="width:'+(v/max*100)+'%"></div></div><b>'+v+'</b></div>').join('')||'<p class="muted">No activity yet.</p>'}
function findings(){const out=[],pairs=analyzeNotePairs(state.events),flood=detectFloods(state.events.slice(-1000));for(const [k,vals] of state.cc){if(PARAM_CCS.has(Number(k.split(':')[1]))||isSwitchLike(vals))continue;const s=controlStats(vals);if(s.count>=10&&s.coverage<75)out.push({sev:'attention',text:k+': limited range observed ('+s.min+'–'+s.max+', '+s.coverage+'% coverage).'});if(s.count>=20&&s.jitter>=4)out.push({sev:'investigate',text:k+': high stationary jitter observed (mean reversal amplitude '+s.jitter+').'});if(s.jumps>=3)out.push({sev:'attention',text:k+': '+s.jumps+' abrupt value jumps observed.'})}const pp=primaryPitch(),ps=pitchStats(pp.values,pp.times);if(ps.centerSamples>=2&&ps.centerSpread>100)out.push({sev:'attention',text:'Pitch bend center-return spread is '+ps.centerSpread+' units across '+ps.centerSamples+' resting samples.'});if(ps.centerSamples&&Math.abs(ps.center)>200)out.push({sev:'attention',text:'Pitch bend rests '+ps.center+' units from center.'});const miss=missingKeys();if(miss.length)out.push({sev:'attention',text:miss.length+' expected key(s) not observed: '+miss.slice(0,12).map(noteName).join(', ')+(miss.length>12?'…':'')+'.'});const sw=switchStats(state.sustainValues,state.sustainTimes);if(sw.bounces)out.push({sev:'attention',text:'Sustain pedal: '+sw.bounces+' quick re-trigger(s) under 40 ms (possible contact bounce).'});if(pairs.stuck.length)out.push({sev:'investigate',text:pairs.stuck.length+' note(s) currently have Note On without matching Note Off.'});if(pairs.duplicateOns)out.push({sev:'attention',text:pairs.duplicateOns+' duplicate Note On event(s) observed.'});if(state.disconnects)out.push({sev:state.disconnects>=2?'investigate':'attention',text:state.disconnects+' MIDI disconnect event(s) observed.'});for(const f of flood)out.push({sev:'attention',text:f.detail});for(const t of testResults())if(t.status==='attention'||t.status==='investigate')out.push({sev:t.status,text:t.title+': '+t.headline+'.'});for(const f of (state.winAnalysis?.findings||[]).filter(x=>x.duringTest&&x.severity!=='info').slice(0,5))out.push({sev:f.severity,text:'Windows log: '+f.title+'.'});if(state.loopback?.result&&(state.loopback.result.missing||state.loopback.result.altered||state.loopback.result.extra))out.push({sev:'investigate',text:'Loopback mismatch: '+state.loopback.result.missing+' missing, '+state.loopback.result.altered+' altered, '+state.loopback.result.extra+' extra.'});return out}
const PARAM_CCS=new Set([6,38,96,97,98,99,100,101]);
// Pitch-bend diagnostics use the channel with the most bend traffic; other channels (e.g. MPE members) are listed separately.
function primaryPitch(){let best=null;for(const [ch,v] of state.pitchByChannel)if(!best||v.values.length>best.values.length)best={channel:ch,...v};return best||{channel:null,values:[],times:[]}}
function missingKeys(){const e=state.expected,out=[];if(e.low===null||e.high===null)return out;for(let n=e.low;n<=e.high;n++)if(!state.keys.has(n))out.push(n);return out}
function renderSummary(){const vr=velocityStats(state.velocityValues);els.summary.innerHTML=[stat('Events',state.events.length.toLocaleString()),stat('Msg/sec',messageRate(state.timestamps).toFixed(0)),stat('Peak/sec',state.peakRate.toFixed(0)),stat('Keys',state.keys.size),stat('Velocity',vr.count?vr.min+'–'+vr.max:'—'),stat('CCs',state.cc.size),stat('Disconnects',state.disconnects)].join('')}
function renderFindings(){const f=findings();els.findings.innerHTML=f.length?f.slice(0,30).map(x=>'<div class="finding '+x.sev+'"><span class="badge">'+(x.sev==='investigate'?'Investigate':'Attention')+'</span><span>'+esc(x.text)+'</span></div>').join(''):'<p class="muted">No suspicious behavior has been measured yet.</p>'}
function mpeLikely(){const expr=state.events.filter(e=>e.channel&&['pitchbend','aftertouch','polyaftertouch'].includes(e.kind)||(e.kind==='cc'&&e.a===74));const channels=new Set(expr.map(e=>e.channel).filter(Boolean));return channels.size>=2&&state.keys.size>=2}
function renderInventory(){const notes=[...state.keys].sort((a,b)=>a-b),inv=[['Notes',notes.length?notes.length+' observed ('+noteName(notes[0])+'–'+noteName(notes.at(-1))+')':'None observed'],...(()=>{let sw=0,rel=0,cont=0;for(const [k,v] of state.cc){if(PARAM_CCS.has(Number(k.split(':')[1])))continue;const c=classifyEncoder(v);if(c.startsWith('Switch'))sw++;else if(c.startsWith('Likely relative'))rel++;else cont++}return [['Continuous controls',cont+' CC stream(s)'],['Buttons / switches',sw?sw+' switch-like CC(s)':'Not observed'],['Relative encoders',rel?rel+' candidate(s)':'Not observed']]})(),['Pitch bend',state.pitchValues.length?'Observed':'Not observed'],['Sustain',state.sustainValues.length?'Observed':'Not observed'],['Channel pressure',state.aftertouch.length?'Observed':'Not observed'],['Poly pressure',state.polyAftertouch.size?state.polyAftertouch.size+' note streams':'Not observed'],['Program change',state.programs.length?state.programs.length+' events':'Not observed'],['MIDI clock',state.clockTimes.length?'Observed':'Not observed'],['14-bit CC pairs',state.hires.length?state.hires.length+' observations':'Not observed'],['RPN / NRPN',state.paramEvents.length?state.paramEvents.length+' decoded updates':'Not observed'],['SysEx',state.sysex.length?state.sysex.length+' captured':(sysexEnabled?'None observed':'Permission not enabled')],['MPE-like activity',mpeLikely()?state.mpe.size+' active expressive channels':'Not currently observed']];els.inventory.innerHTML='<div class="inventory-list">'+inv.map(([a,b])=>'<div class="inventory-item"><strong>'+esc(a)+'</strong><span>'+esc(b)+'</span></div>').join('')+'</div>'}
function renderMessages(){els.messageStats.innerHTML=meterRows(Object.entries(state.messageCounts).sort((a,b)=>b[1]-a[1]));const cs=channelStats(state.events),rows=[];for(const [ch,v] of Object.entries(cs))rows.push(['Ch '+ch+' · notes '+v.noteon+' · CC '+v.cc+' · bend '+v.pitchbend,v.total]);els.channels.innerHTML=meterRows(rows)}
function controlName(cc){return cc===1?'Mod Wheel':cc===11?'Expression':cc===64?'Sustain':'CC '+cc}
function renderControls(){const items=[...state.cc.entries()].sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true}));els.controls.innerHTML=items.length?items.map(([k,v])=>{const [ch,cc]=k.split(':').map(Number);return '<button type="button" class="control-card '+(selectedControl===k?'selected':'')+'" aria-pressed="'+(selectedControl===k)+'" data-control="'+k+'"><strong>Ch '+ch+' · '+controlName(cc)+'</strong><small>'+esc(classifyEncoder(v))+'</small><b>'+(v.length?v.at(-1):'—')+'</b></button>'}).join(''):'<p class="muted">Move a control to begin profiling.</p>';if(!selectedControl&&items.length){selectedControl=items[0][0];renderControls();return}renderControlDetail();const pedal=[];for(const cc of [1,11,64])for(const [k,v] of state.cc)if(Number(k.split(':')[1])===cc){const s=controlStats(v);let extra='';if(cc===64){const sw=switchStats(state.sustainValues,state.sustainTimes);extra=' · '+sw.transitions+' on/off transitions, '+sw.bounces+' bounce(s), '+sw.repeats+' repeated state messages'+(s.unique>2?' · '+s.unique+' distinct values (half-damper/continuous capable)':'')+(sw.state?' · now '+sw.state:'')}pedal.push(k+' '+controlName(cc)+': '+s.min+'–'+s.max+(isSwitchLike(v)?' (switch)':', jitter '+s.jitter)+', '+s.unique+' values'+extra)}els.pedalStats.innerHTML=pedal.length?pedal.map(x=>'<p>'+esc(x)+'</p>').join(''):'<p class="muted">No mod/expression/sustain activity observed.</p>';const at=controlStats(state.aftertouch);els.aftertouchStats.innerHTML=at.count?'<p>Channel pressure: '+at.min+'–'+at.max+', jitter '+at.jitter+'</p>':'<p class="muted">No channel pressure observed.</p>';for(const [k,v] of state.polyAftertouch){const s=controlStats(v);els.aftertouchStats.innerHTML+='<p>Poly '+esc(k)+': '+s.min+'–'+s.max+', jitter '+s.jitter+'</p>'}els.hiresStats.innerHTML=(state.hires.slice(-6).map(x=>'<p>Ch '+x.channel+' CC'+x.msbCc+'/'+x.lsbCc+': '+x.value14+'</p>').join('')+state.paramEvents.slice(-6).map(x=>'<p>'+x.type+' Ch '+x.channel+' param '+x.parameter+': '+x.value14+(x.increment?' Δ'+x.increment:'')+'</p>').join(''))||'<p class="muted">No paired 14-bit CC or RPN/NRPN activity observed.</p>'}
function renderPitch(){const pp=primaryPitch(),ps=pitchStats(pp.values,pp.times),others=[...state.pitchByChannel.keys()].filter(c=>c!==pp.channel);if(!ps.count){els.pitchStats.innerHTML='<p class="muted">No pitch bend observed.</p>';els.pitchRange.style.cssText='';els.pitchNow.style.cssText='display:none';return}const pct=v=>((v+8192)/16383*100).toFixed(2)+'%';els.pitchStats.innerHTML='<p>Channel '+pp.channel+(others.length?' · also seen on channel(s) '+others.join(', ')+' (see MPE-like activity)':'')+'</p><div class="metric-grid">'+metric('Current',pp.values.at(-1))+metric('Min',ps.min)+metric('Max',ps.max)+metric('Negative travel',ps.negativeTravel)+metric('Positive travel',ps.positiveTravel)+metric('Asymmetry',ps.asymmetry)+metric('Resting center',ps.center??'—')+metric('Center spread',ps.centerSpread??'—')+metric('Rest samples',ps.centerSamples)+metric('Samples',ps.count)+'</div>';els.pitchRange.style.cssText='left:'+pct(ps.min)+';width:calc('+pct(ps.max)+' - '+pct(ps.min)+')';els.pitchNow.style.cssText='left:'+pct(pp.values.at(-1))}
function renderMpe(){const rows=[...state.mpe.entries()].sort((a,b)=>a[0]-b[0]);const likely=mpeLikely();els.mpeStats.innerHTML=rows.length?'<p>'+(likely?'MPE-like traffic: ':'Active note channels: ')+rows.length+' channel(s)</p><div class="compact-table">'+rows.map(([ch,v])=>'<div class="compact-row"><strong>Ch '+ch+'</strong><small>'+esc(noteName(v.note))+'</small><span>bend '+v.pitch+' · pressure '+v.pressure+' · CC74 '+v.timbre+'</span></div>').join('')+'</div>':'<p class="muted">No per-channel expressive note activity currently held.</p>'}
function renderSysex(){if(!state.sysex.length){els.sysexStats.innerHTML='<p class="muted">'+(sysexEnabled?'No SysEx observed yet.':'SysEx permission not enabled. Use Enable SysEx in the session bar.')+'</p>';return}const groups=new Map();for(const x of state.sysex){const g=groups.get(x.hex)||{...x,count:0};g.count++;g.t=x.t;groups.set(x.hex,g)}const mfr=x=>x.manufacturer===null?'—':x.manufacturer===0?'00 '+(x.hex.split(' ').slice(2,4).join(' ')):x.manufacturer.toString(16).padStart(2,'0').toUpperCase();els.sysexStats.innerHTML='<p>'+state.sysex.length+' message(s), '+groups.size+' unique</p><div class="sysex-list">'+[...groups.values()].slice(-30).reverse().map(g=>'<div class="sysex-item"><div><strong>'+g.length+' bytes</strong> · manufacturer ID '+esc(mfr(g))+' · seen '+g.count+'× · last '+(g.t/1000).toFixed(3)+'s</div><code>'+esc(g.hex.length>600?g.hex.slice(0,600)+' …':g.hex)+'</code></div>').join('')+'</div>'}
function renderControlDetail(){if(!selectedControl||!state.cc.has(selectedControl)){els.controlTitle.textContent='No control selected.';els.controlDetail.innerHTML='';drawControl([]);histogram(els.controlHistogram,[]);return}const vals=state.cc.get(selectedControl),times=state.ccTimes.get(selectedControl)||[],s=controlStats(vals),[ch,cc]=selectedControl.split(':').map(Number);els.controlTitle.textContent='Channel '+ch+' · '+controlName(cc);els.controlDetail.innerHTML='<div class="metric-grid">'+metric('Current',vals.at(-1))+metric('Range',s.min+'–'+s.max)+metric('Coverage',s.coverage+'%')+metric('Unique',s.unique)+metric('Skipped',s.skipped)+metric('Repeated',s.repeated)+metric('Jitter',s.jitter)+metric('Jumps',s.jumps)+metric('Reversals',s.reversals)+metric('Event/sec',messageRate(times,1000).toFixed(1))+metric('Encoder',classifyEncoder(vals))+metric('Dead zones',s.deadZones.length?s.deadZones.map(z=>z[0]+'–'+z[1]).join(', '):'none')+'</div>';drawControl(vals.slice(-200));const bins=Array(16).fill(0);for(const v of vals)bins[Math.min(15,Math.floor(v/8))]++;histogram(els.controlHistogram,bins)}
function drawControl(values){const c=els.controlGraph,ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#26394b';ctx.beginPath();for(let i=0;i<=4;i++){const y=i*h/4;ctx.moveTo(0,y);ctx.lineTo(w,y)}ctx.stroke();if(values.length<2)return;ctx.strokeStyle='#6ba1cf';ctx.lineWidth=3;ctx.beginPath();values.forEach((v,i)=>{const x=i/(values.length-1)*w,y=h-(v/127*h);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function renderKeyboard(){const seen=[...state.keys].sort((a,b)=>a-b),low=state.expected.low??(seen.length?Math.max(0,seen[0]-2):48),high=state.expected.high??(seen.length?Math.min(127,Math.max(seen.at(-1)+2,low+23)):71),missing=[];if(state.expected.low!==null&&state.expected.high!==null)for(let n=state.expected.low;n<=state.expected.high;n++)if(!state.keys.has(n))missing.push(n);els.keySummary.textContent=seen.length?seen.length+' notes observed · '+noteName(seen[0])+' to '+noteName(seen.at(-1))+(missing.length?' · '+missing.length+' expected notes unseen':''):'No notes observed.';let html='';for(let n=low;n<=high;n++){const black=[1,3,6,8,10].includes(n%12);html+='<div class="key '+(black?'black ':'')+(state.keys.has(n)?'seen ':'')+(state.held.has(n)?'held ':'')+(missing.includes(n)?'missing':'')+'" title="'+esc(noteName(n))+'">'+esc(noteName(n))+'</div>'}els.keyboard.innerHTML=html;const held=[...state.held].sort((a,b)=>a-b),chord=chordName(held);els.held.innerHTML=(held.map(n=>'<span>'+esc(noteName(n))+'</span>').join('')||'<span>None</span>')+(chord?'<span>Chord: '+esc(chord)+'</span>':'');const p=analyzeNotePairs(state.events);els.notePairStats.innerHTML='<p>Completed notes: '+p.completed.length+' · duplicate Note On: '+p.duplicateOns+' · duplicate Note Off: '+p.duplicateOffs+' · currently unmatched: '+p.stuck.length+'</p>';const vs=velocityStats(state.velocityValues);els.velocityStats.innerHTML=vs.count?'<div class="metric-grid">'+metric('Samples',vs.count)+metric('Min',vs.min)+metric('Max',vs.max)+metric('Mean',vs.mean)+metric('Median',vs.median)+metric('Std dev',vs.stdev)+metric('Range',vs.range)+'</div>':'<p class="muted">No Note On velocity samples observed.</p>';histogram(els.velocityHistogram,vs.histogram||[]);els.perKeyVelocity.innerHTML=[...state.velocityByKey.entries()].sort((a,b)=>a[0]-b[0]).map(([n,v])=>{const s=velocityStats(v);return '<div class="compact-row"><strong>'+noteName(n)+'</strong><small>'+s.count+' samples</small><span>'+s.min+'–'+s.max+' · μ '+s.mean+' · σ '+s.stdev+'</span></div>'}).join('')||'<p class="muted">No per-key samples.</p>'}
function renderTiming(){const cs=clockStats(state.clockTimes);const rb=rollingBpm(state.clockTimes),tr=metric('Transport',state.transport.at(-1)?.kind||'—')+metric('Song position',state.songPosition===null?'—':state.songPosition+' (beat '+(state.songPosition/4+1).toFixed(2)+')');els.clock.innerHTML=(cs.bpm?'<div class="metric-grid">'+metric('BPM (median)',cs.bpm.toFixed(2))+metric('Rolling BPM',rb?rb.toFixed(2):'—')+metric('Ticks',cs.count)+metric('Interval ms',cs.intervalMean)+metric('Interval min–max',cs.intervalMin.toFixed(2)+'–'+cs.intervalMax.toFixed(2))+metric('Mean jitter ms',cs.jitter)+metric('Peak jitter ms',cs.peakJitter)+tr+'</div>':'<p class="muted">No stable MIDI clock observed'+(cs.count?' ('+cs.count+' ticks so far; 25 needed)':'')+'.</p>'+(state.transport.length||state.songPosition!==null?'<div class="metric-grid">'+tr+'</div>':''));histogram(els.clockHistogram,cs.bpm?cs.histogram:[]);const ps=performanceStats(state.events),dur=ps.notes.map(n=>n.duration).filter(Number.isFinite),ioi=ps.interOnset;const f=x=>x===null?'—':Number(x).toFixed(1);els.performanceStats.innerHTML=ps.notes.length?'<div class="metric-grid">'+metric('Note events',ps.notes.length)+metric('Completed',dur.length)+metric('Held candidates',ps.held.length)+metric('Duration mean ms',f(ps.durationStats.mean))+metric('Duration min–max ms',ps.durationStats.count?f(ps.durationStats.min)+'–'+f(ps.durationStats.max):'—')+metric('Inter-onset median ms',f(ps.interOnsetStats.median))+metric('Inter-onset σ ms',f(ps.interOnsetStats.stdev))+metric('Chord groups (≤12 ms)',ps.simultaneousGroups.length)+metric('Chord spread mean ms',f(ps.chordSpreadStats.mean))+'</div>':'<p class="muted">No note timing data yet.</p>';const fl=detectFloods(state.events.slice(-1500));els.floods.innerHTML=fl.length?fl.map(x=>'<div class="finding attention"><span class="badge">Observe</span><span>'+esc(x.detail)+'</span></div>').join(''):'<p class="muted">No flood patterns detected in the recent window.</p>';const lb=state.loopback?.result;els.loopbackStats.innerHTML=lb?'<div class="metric-grid">'+metric('Sent',lb.sent)+metric('Received',lb.received)+metric('Matched',lb.matched)+metric('Altered',lb.altered)+metric('Missing',lb.missing)+metric('Extra',lb.extra)+metric('Completion',lb.completion+'%')+'</div>':'<p class="muted">No loopback run completed.</p>';const ls=latencyStats(state.latencies);els.latencyStats.innerHTML=ls.count?'<div class="metric-grid">'+metric('Samples',ls.count)+metric('Min ms',ls.min.toFixed(2))+metric('Median ms',ls.median.toFixed(2))+metric('Mean ms',ls.mean.toFixed(2))+metric('Max ms',ls.max.toFixed(2))+metric('Std dev',ls.stdev.toFixed(2))+'</div>':'<p class="muted">No matched loopback latency samples.</p>';const bins=Array(12).fill(0);if(state.latencies.length){const max=Math.max(...state.latencies,1);for(const x of state.latencies)bins[Math.min(11,Math.floor(x/max*12))]++}histogram(els.latencyHistogram,bins)}
function renderLearn(){if(!lastDecoded){els.learn.textContent='Waiting for a message…';return}const s=lastDecoded.kind==='cc'?controlStats(state.cc.get(lastDecoded.channel+':'+lastDecoded.a)||[]):null;els.learn.textContent=lastDecoded.label+' / Channel '+(lastDecoded.channel??'—')+' / value '+lastDecoded.value+(s?.count?' / range '+s.min+'-'+s.max:'')+' / '+lastDecoded.hex}
function renderMappings(){els.mappingRows.innerHTML=state.mappings.map((m,i)=>'<tr><td>'+esc(m.message)+'</td><td contenteditable="true" data-edit="'+i+'">'+esc(m.label)+'</td><td><button data-remove="'+i+'" aria-label="Remove mapping">×</button></td></tr>').join('');$$('[data-remove]').forEach(b=>b.onclick=()=>{state.mappings.splice(Number(b.dataset.remove),1);renderMappings();renderReport()});$$('[data-edit]').forEach(c=>c.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();c.blur()}});$$('[data-edit]').forEach(c=>c.onblur=()=>{state.mappings[Number(c.dataset.edit)].label=c.textContent.trim();renderReport()})}
function controlSnapshot(){const controls={};for(const [k,v] of state.cc)controls[k]={...controlStats(v),encoder:classifyEncoder(v),last:v.at(-1)};return controls}
function untestedAreas(){const a=[];for(const x of state.guidedSkipped)a.push('Guided step skipped: '+x);if(!state.keys.size)a.push('No notes/keys observed');if(!state.cc.size)a.push('No continuous controls observed');if(!state.pitchValues.length)a.push('Pitch bend not observed');if(!state.sustainValues.length)a.push('Sustain pedal (CC64) not observed');if(state.expected.low===null)a.push('Expected key range not set; missing keys not computed');if(!state.aftertouch.length&&!state.polyAftertouch.size)a.push('Aftertouch not observed');if(!state.clockTimes.length)a.push('MIDI clock not observed/tested');if(!state.loopback)a.push('Loopback/latency not tested');if(!sysexEnabled)a.push('SysEx permission not enabled');if(!state.paramEvents.length)a.push('RPN/NRPN not observed');if(!state.winAnalysis)a.push('Windows MIDI/USB logs not scanned');return a}
function buildReport(){const controls=controlSnapshot(),pair=analyzeNotePairs(state.events),pp=primaryPitch(),ps={...pitchStats(pp.values,pp.times),channel:pp.channel},vs=velocityStats(state.velocityValues),cs=clockStats(state.clockTimes),report=reportSummary({...state,controls,pitch:ps});Object.assign(report,{generatedAt:new Date().toISOString(),preset:els.preset.value,sysexEnabled,velocity:vs,notePairing:pair,aftertouch:controlStats(state.aftertouch),polyAftertouch:Object.fromEntries([...state.polyAftertouch].map(([k,v])=>[k,controlStats(v)])),clock:cs,transport:state.transport,songPosition:state.songPosition,messageRate:{current:messageRate(state.timestamps),peak:state.peakRate,average:state.events.length/Math.max(1,(Date.now()-state.started)/1000)},channelStats:channelStats(state.events),floods:detectFloods(state.events.slice(-1500)),highResolutionCc:state.hires.slice(-100),parameters:state.paramEvents.slice(-100),mpeLike:mpeLikely()?[...state.mpe.entries()].map(([channel,v])=>({channel,...v})):[],sysex:state.sysex,mappings:state.mappings,connections:state.connections,latency:latencyStats(state.latencies),loopback:state.loopback?.result||null,observations:findings().map(x=>({severity:x.sev,text:x.text})),untested:untestedAreas(),advancedTests:testResults().map(t=>({id:t.id,title:t.title,status:t.status,headline:t.headline,metrics:Object.fromEntries(t.metrics),details:t.rows,meaning:t.meaning})),windowsLogs:state.winAnalysis?{status:state.winAnalysis.status,counts:state.winAnalysis.counts,meta:state.winAnalysis.meta,findings:state.winAnalysis.findings.slice(0,60).map(({severity,title,source,time,duringTest,explain,action})=>({severity,title,source,time,duringTest,explain,action})),devices:state.winAnalysis.devices.map(d=>({name:d.name,id:d.id,errorCode:d.errorCode,problem:d.problem?.title||null})),logs:state.winAnalysis.logs.slice(0,40)}:null,logFiles:state.logAnalyses,expected:state.expected,missingKeys:missingKeys(),reconnects:state.reconnects,sustain:switchStats(state.sustainValues,state.sustainTimes),guided:{skipped:state.guidedSkipped,ended:state.guidedEnded}});for(const f of reportExtensions)try{f(report)}catch(e){console.error('report extension failed',e)}return report}
function reportRow(label,value){return '<tr><th scope="row">'+esc(label)+'</th><td>'+esc(value)+'</td></tr>'}
function renderComparison(c,old,cur){const sign=v=>(v>0?'+':'')+v;const changed=Object.entries(c.controls).filter(([,v])=>v.missing||v.new||v.rangeDelta||Math.abs(v.jitterDelta)>=0.5);return '<h3>Baseline comparison</h3><p class="muted">Compared with report generated '+esc(old.generatedAt||'(unknown time)')+(old.device?' for '+esc(old.device):'')+'.</p><table class="report-table">'+reportRow('Keys missing vs baseline',c.missingKeys.length?c.missingKeys.map(noteName).join(', '):'none')+reportRow('New keys vs baseline',c.newKeys.length)+reportRow('Disconnect delta',sign(c.disconnectDelta))+reportRow('Pitch-bend center delta',sign(c.pitchCenterDelta))+reportRow('Latency median delta (ms)',sign(Number(c.latencyMedianDelta.toFixed(2))))+reportRow('Peak message rate delta',sign(Number(c.peakRateDelta.toFixed(1))))+'</table>'+(changed.length?'<h4>Control changes</h4><table class="report-table">'+changed.slice(0,40).map(([k,v])=>reportRow(k,v.missing?'not observed this session':v.new?'new this session':'range '+sign(v.rangeDelta)+', jitter '+sign(v.jitterDelta))).join('')+'</table>':'<p>No control range/jitter changes.</p>')}
function renderReport(){const r=buildReport(),compare=state.importedReport?baselineDiff(state.importedReport,r):null;els.reportPreview.textContent=JSON.stringify(r,null,2);const ctrl=Object.entries(r.controls),fmtRange=(a,b)=>a===null?'—':a+'–'+b,keys=r.keys;
const summary='<table class="report-table">'+reportRow('Device',r.device||'(no input selected)')+reportRow('Preset',r.preset)+reportRow('Test duration',formatElapsed(r.durationMs))+reportRow('Events captured',r.eventCount)+reportRow('Keys observed',keys.length?keys.length+' ('+noteName(keys[0])+'–'+noteName(keys.at(-1))+')':'none')+reportRow('Missing expected keys',r.expected.low===null?'expected range not set':r.missingKeys.length?r.missingKeys.map(noteName).join(', '):'none')+reportRow('Note pairing',r.notePairing.completed.length+' completed, '+r.notePairing.duplicateOns+' duplicate On, '+r.notePairing.duplicateOffs+' duplicate Off, '+r.notePairing.stuck.length+' unmatched')+reportRow('Velocity',r.velocity.count?fmtRange(r.velocity.min,r.velocity.max)+' · mean '+r.velocity.mean+' · σ '+r.velocity.stdev:'not observed')+reportRow('Detected controls',ctrl.length?ctrl.length+' CC stream(s)':'none')+reportRow('Pitch bend',r.pitch.count?fmtRange(r.pitch.min,r.pitch.max)+' · rest center '+(r.pitch.center??'—')+' · spread '+(r.pitch.centerSpread??'—'):'not observed')+reportRow('Sustain pedal',r.sustain.state===null?'not observed':r.sustain.transitions+' transitions, '+r.sustain.bounces+' bounce(s)')+reportRow('Aftertouch',r.aftertouch.count?'channel '+fmtRange(r.aftertouch.min,r.aftertouch.max):Object.keys(r.polyAftertouch).length?'poly, '+Object.keys(r.polyAftertouch).length+' note stream(s)':'not observed')+reportRow('Message rate',r.messageRate.current.toFixed(0)+'/s now · peak '+r.messageRate.peak.toFixed(0)+'/s · average '+r.messageRate.average.toFixed(1)+'/s')+reportRow('Channels used',r.channels.join(', ')||'none')+reportRow('Disconnects / reconnects',r.disconnects+' / '+r.reconnects)+reportRow('MIDI clock',r.clock.bpm?r.clock.bpm.toFixed(2)+' BPM · jitter '+r.clock.jitter+' ms':'not observed')+reportRow('Loopback',r.loopback?r.loopback.matched+'/'+r.loopback.sent+' matched · '+r.loopback.missing+' missing · '+r.loopback.altered+' altered · '+r.loopback.extra+' extra':'not run')+reportRow('Round-trip latency',r.latency.count?'median '+r.latency.median.toFixed(2)+' ms ('+r.latency.count+' samples)':'not measured')+reportRow('Advanced tests',r.advancedTests.filter(t=>t.status==='investigate').length+' investigate, '+r.advancedTests.filter(t=>t.status==='attention').length+' attention, '+r.advancedTests.filter(t=>t.status==='ok').length+' no concern')+reportRow('Windows logs',r.windowsLogs?r.windowsLogs.counts.investigate+' investigate, '+r.windowsLogs.counts.attention+' attention ('+r.windowsLogs.counts.duringTest+' during tests)':'not scanned')+'</table>';
const ctrlTable=ctrl.length?'<h3>Controls</h3><table class="report-table"><thead><tr><th>Control</th><th>Range</th><th>Coverage</th><th>Jitter</th><th>Jumps</th><th>Type</th></tr></thead><tbody>'+ctrl.slice(0,64).map(([k,v])=>'<tr><td>'+esc(k)+'</td><td>'+fmtRange(v.min,v.max)+'</td><td>'+v.coverage+'%</td><td>'+v.jitter+'</td><td>'+v.jumps+'</td><td>'+esc(v.encoder)+'</td></tr>').join('')+'</tbody></table>':'';
els.reportHuman.innerHTML='<div class="grid two"><div><h3>Findings</h3>'+(r.observations.length?r.observations.map(x=>'<div class="finding '+x.severity+'"><span class="badge">'+esc(x.severity)+'</span><span>'+esc(x.text)+'</span></div>').join(''):'<p class="muted">No suspicious measurements currently highlighted.</p>')+'<h3>Untested / not observed</h3>'+(r.untested.map(x=>'<p>'+esc(x)+'</p>').join('')||'<p>All optional areas produced observations.</p>')+'</div><div><h3>Summary</h3>'+summary+'</div></div>'+ctrlTable+(compare?renderComparison(compare,state.importedReport,r):'')}
function formatElapsed(ms){const s=Math.floor(ms/1000),m=Math.floor(s/60);return String(m).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
const viewRenderers={quick:()=>{renderFindings();renderInventory()},monitorView:()=>{renderMessages();renderSysex()},controlsView:()=>{renderControls();renderPitch();renderMpe()},keyboardView:renderKeyboard,timingView:renderTiming,outputView:()=>{},testsView:renderTests,winlogView:renderWin,mappingView:renderLearn,reportView:renderReport};
function activeView(){return document.querySelector('.view.active-view')?.id||'quick'}
// force=true renders every view (used after resets and before print/export); otherwise only the visible view.
function renderAll(force=false){renderSummary();if(force){for(const f of Object.values(viewRenderers))f()}else viewRenderers[activeView()]?.();els.elapsed.textContent=formatElapsed(Date.now()-state.started)}
function download(name,text,type='text/plain'){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function csv(rows){return rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n')}
function send(bytes){if(!currentOutput){setStatus('Select a MIDI output first.','attention');return false}currentOutput.send(bytes);return true}
function outChannel(){return clamp(els.outChannel.value,1,16)-1}
function sendNote(on){send([(on?0x90:0x80)|outChannel(),clamp(els.outNote.value,0,127),on?clamp(els.outVelocity.value,0,127):0])}
function sendCc(){send([0xB0|outChannel(),clamp(els.outCc.value,0,127),clamp(els.outCcValue.value,0,127)])}
function sendProgram(){send([0xC0|outChannel(),clamp(els.outProgram.value,0,127)])}
function sendPitch(){const v=clamp(els.outPitch.value,-8192,8191)+8192;send([0xE0|outChannel(),v&0x7f,(v>>7)&0x7f])}
function panic(channels){for(const ch of channels){send([0xB0|ch,120,0]);send([0xB0|ch,121,0]);send([0xB0|ch,123,0])}}
function runLoopback(){state.testWindowStart=Date.now();if(!currentInput||!currentOutput){setStatus('Select both an input and an output for loopback.','attention');return}if(state.loopback?.active){setStatus('Loopback already running.','attention');return}const ch=outChannel(),rounds=clamp(els.loopRounds.value,1,20),messages=[];for(let r=0;r<rounds;r++){const n=(60+r)&0x7f,seq=(r*7+17)&0x7f,pb=(8192+(r+1)*256)&0x3fff;messages.push([0x90|ch,n,37+r],[0x80|ch,n,0],[0xB0|ch,21,seq],[0xC0|ch,(9+r)&0x7f],[0xE0|ch,pb&0x7f,pb>>7],[0xB0|ch,21,(seq+86)&0x7f])}messages.push([0xE0|ch,0,64]);state.loopback={active:true,sent:messages.map(bytes=>({bytes,t:null,matched:false})),received:[],started:performance.now(),result:null};state.latencies=[];els.runLoopback.disabled=true;messages.forEach((m,i)=>setTimeout(()=>{const item=state.loopback?.sent[i];if(!item||!currentOutput)return;item.t=performance.now();currentOutput.send(m);if(i===messages.length-1)setTimeout(finishLoopback,700)},i*40));setStatus('Loopback sequence sending ('+messages.length+' messages); waiting for returned messages.','connected')}
function matchLoopback(e){if(!state.loopback?.active||e.raw[0]>=0xF8)return false;state.loopback.received.push({bytes:e.raw,t:e.t});const candidate=state.loopback.sent.find(s=>!s.matched&&s.t!==null&&s.bytes.length===e.raw.length&&s.bytes.every((v,i)=>v===e.raw[i]));if(candidate){candidate.matched=true;state.latencies.push(Math.max(0,e.t-candidate.t));return true}return false}
function finishLoopback(){if(!state.loopback)return;maybeAutoScan('the loopback test');state.loopback.active=false;state.loopback.result=compareLoopback(state.loopback.sent.map(x=>x.bytes),state.loopback.received.map(x=>x.bytes));updateHardwareControls();setStatus('Loopback test complete. Review Timing results.','connected');renderAll(true)}
function guidedRender(){const step=guidedSteps[state.guidedStep]||guidedSteps.at(-1);els.guidedTitle.textContent=state.guided?(state.guidedStep+1)+'/'+guidedSteps.length+' · '+step[0]:'Ready';els.guidedText.textContent=state.guided?step[1]:'Enable MIDI and select an input, or use the monitor directly.';els.guided.textContent=state.guided?'Restart Guided Test':'Start Guided Test';els.guidedBack.disabled=!state.guided||state.guidedStep===0;els.guidedNext.disabled=!state.guided||state.guidedStep===guidedSteps.length-1;els.guidedSkip.disabled=!state.guided||state.guidedStep===guidedSteps.length-1;els.guidedEnd.disabled=!state.guided;if(state.guidedEnded){els.guidedTitle.textContent='Guided test ended';els.guidedText.textContent='Data is kept. Review the Report tab'+(state.guidedSkipped.length?' — skipped: '+state.guidedSkipped.join(', '):'')+'.'}}
function startGuided(){resetState(true);state.guided=true;state.guidedEnded=false;state.guidedStep=0;state.guidedSkipped=[];guidedRender();const hints={'Keyboard Controller':' Emphasize key sweep, velocity, pedals and pitch bend.','Pad Controller':' Emphasize pad coverage, velocity consistency and aftertouch.','DJ Controller':' Emphasize encoders, faders, buttons and message flood behavior.','Foot Controller':' Emphasize pedals, switches and reconnect stability.','Hardware Synth':' Emphasize bidirectional output, program changes, SysEx and clock.'};els.guidedText.textContent+=hints[els.preset.value]||'';setStatus('Guided diagnostic started.','connected')}
function skipGuided(){if(!state.guided)return;const name=guidedSteps[state.guidedStep][0];if(!state.guidedSkipped.includes(name))state.guidedSkipped.push(name);changeGuided(1)}
function endGuided(){if(!state.guided)return;maybeAutoScan('the guided test');state.guided=false;state.guidedEnded=true;guidedRender();renderAll(true);setStatus('Guided test ended. Review the Report tab.','connected')}
function changeGuided(delta){if(!state.guided)return;state.guidedStep=clamp(state.guidedStep+delta,0,guidedSteps.length-1);guidedRender();renderReport()}

// ---------- Advanced tests ----------
function testResults(){const pp=primaryPitch();return buildTestResults({events:state.events.filter(e=>!e.loopback),velocityByKey:state.velocityByKey,velocityValues:state.velocityValues,cc:state.cc,ccTimes:state.ccTimes,paramCcs:PARAM_CCS,pitchValues:pp.values,pitchTimes:pp.times,sustainValues:state.sustainValues,sustainTimes:state.sustainTimes,expectedPoly:Number(els.polyExpected.value)||null,burst:state.burst})}
let testsHtml='';
function renderTests(){
 const open=new Set([...els.testResults.querySelectorAll('details[open]')].map(d=>d.dataset.id));
 const html=testResults().map(t=>{const g=TEST_GUIDE[t.id];return '<article class="panel test-card"><div class="section-head"><div><h3>'+esc(t.title)+'</h3><p>'+esc(t.kind)+' · '+esc(t.headline)+'</p></div><span class="status-chip status-'+t.status+'">'+STATUS_ICON[t.status]+' '+esc(STATUS_LABEL[t.status])+'</span></div><div class="metric-grid">'+t.metrics.map(([a,b])=>metric(a,b)).join('')+'</div>'+(t.rows.length?'<div class="test-rows">'+t.rows.map(r=>'<p>'+esc(r)+'</p>').join('')+'</div>':'')+'<h4>What this result means</h4>'+t.meaning.map(m=>'<p>'+esc(m)+'</p>').join('')+'<details data-id="'+t.id+'"'+(open.has(t.id)?' open':'')+'><summary>How to run · how it works · limits</summary><p><strong>How to run:</strong> '+esc(g.run)+'</p><p><strong>How to read it:</strong> '+esc(g.reads)+'</p><p><strong>Limits:</strong> '+esc(g.limits)+'</p><p><strong>Terms:</strong> '+(TEST_TERMS[t.id]||[]).map(x=>'<button type="button" class="term" data-term="'+esc(x)+'">'+esc(x.replace(/-/g,' '))+'</button>').join(' ')+'</p></details></article>'}).join('');
 if(html!==testsHtml){testsHtml=html;els.testResults.innerHTML=html}
}
function runBurst(){
 if(!currentInput||!currentOutput){setStatus('Select both an input and an output (looped back) for the burst test.','attention');return}
 if(state.burst?.active||state.loopback?.active){setStatus('Another loopback-based test is already running.','attention');return}
 const per=clamp(els.burstCount.value,20,500),ch=outChannel(),base=performance.now();let seq=0,offset=100;
 const stages=[['50 msg/s',50],['250 msg/s',250],['1000 msg/s',1000],['Instant burst',0]].map(([label,rate])=>{const sent=[],sched=[];for(let i=0;i<per;i++){sent.push(seq++);sched.push(base+offset+(rate?i*1000/rate:0))}offset+=(rate?per*1000/rate:0)+400;return {label,rate,sent,sched,received:[],latencies:[]}});
 state.burst={active:true,ch,stages,started:base};state.testWindowStart=Date.now();
 for(const st of stages)st.sent.forEach((q,i)=>currentOutput.send([0xE0|ch,q&0x7f,(q>>7)&0x7f],st.sched[i]));
 els.burstStatus.textContent='Burst test running ('+stages.length*per+' messages, about '+Math.ceil(offset/1000)+' s)…';updateHardwareControls();
 setTimeout(finishBurst,offset+800);
}
function matchBurst(e){const b=state.burst;if(!b?.active||e.kind!=='pitchbend'||e.channel!==b.ch+1)return false;const q=e.raw[1]|(e.raw[2]<<7),st=b.stages.find(s=>q>=s.sent[0]&&q<=s.sent.at(-1));if(!st)return false;st.received.push(q);st.latencies.push(Math.max(0,e.t-st.sched[q-st.sent[0]]));return true}
function finishBurst(){const b=state.burst;if(!b)return;b.active=false;try{currentOutput?.send([0xE0|b.ch,0,64])}catch{}els.burstStatus.textContent='Burst test complete. See the Burst card below.';updateHardwareControls();maybeAutoScan('the burst test');renderAll(true)}

// ---------- Windows logs ----------
const desktop=window.miditestDesktop||null;let scanBusy=false,lastAutoScan=0;
const winHints=()=>[currentInput,currentOutput].filter(Boolean).map(portName);
function applyScan(scan){state.winScan=scan;state.winAnalysis=analyzeWindowsScan(scan,{hints:winHints(),windowStart:state.testWindowStart});renderWin();scheduleRender()}
async function runWinScan(reason='manual request'){
 if(!desktop||desktop.platform!=='win32'){els.winStatus.textContent='Live scanning needs the MIDItest Windows desktop app. In a browser, use "Copy PowerShell scan", run it on the PC, then import the JSON it saves.';return}
 if(scanBusy)return;scanBusy=true;lastAutoScan=Date.now();els.winScan.disabled=true;els.winStatus.textContent='Scanning Windows logs after '+reason+' (can take 10–60 s)…';
 try{const r=await desktop.scanWindows(clamp(els.winDays.value,1,30));if(r.error)els.winStatus.textContent=r.error;else{applyScan(r.scan);const a=state.winAnalysis;els.winStatus.textContent='Scan complete: '+a.counts.investigate+' to investigate, '+a.counts.attention+' attention, '+a.counts.duringTest+' during the current test window.'}}
 catch(e){els.winStatus.textContent='Scan failed: '+(e?.message||e)}
 finally{scanBusy=false;els.winScan.disabled=false}
}
function maybeAutoScan(reason){if(desktop?.platform==='win32'&&!scanBusy&&Date.now()-lastAutoScan>60000)setTimeout(()=>runWinScan(reason),1500)}
const sevClass=s=>s==='investigate'?'investigate':s==='attention'?'attention':'';
function renderWin(){
 const a=state.winAnalysis,out=[];
 if(!a&&!state.logAnalyses.length)out.push('<article class="panel"><h2>No Windows scan yet</h2><p>'+(desktop?.platform==='win32'?'Press Scan Windows logs, or run a test: the scan runs automatically afterwards.':'This view analyses Windows logs. In a browser: press <strong>Copy PowerShell scan</strong>, paste it into a PowerShell window on the Windows PC (it is read-only and saves miditest-windows-scan.json to the Desktop), then use <strong>Import scan / log file</strong>. You can also import setupapi.dev.log (C:\\Windows\\INF) or a WER Report.wer file to have it explained.')+'</p></article>');
 if(a){
  out.push('<article class="panel"><div class="section-head"><div><h2>Scan summary</h2><p>'+esc(a.meta.os||'Windows')+' · scanned '+esc(a.meta.generated||'')+' · last '+esc(a.meta.days)+' day(s) · '+a.meta.eventsRead+' relevant event(s) read</p></div><span class="status-chip status-'+a.status+'">'+esc(a.status==='ok'?'No MIDI/USB errors found':a.status==='investigate'?'Investigate':'Attention')+'</span></div><div class="metric-grid">'+metric('Investigate',a.counts.investigate)+metric('Attention',a.counts.attention)+metric('Info',a.counts.info)+metric('During this test',a.counts.duringTest)+'</div>'+(a.meta.errors.length?'<p class="muted">Some logs could not be read (normal without Administrator rights): '+esc(a.meta.errors.slice(0,4).join(' | '))+'</p>':'')+'</article>');
  out.push('<article class="panel"><h2>Findings and what they mean</h2>'+(a.findings.length?a.findings.slice(0,60).map(f=>'<div class="win-finding"><span class="tag '+(f.duringTest?'now':'')+'">'+esc(f.severity)+'</span>'+(f.duringTest?'<span class="tag now">during this test</span>':'')+(f.mentionsDevice?'<span class="tag">mentions your device</span>':'')+'<h3>'+esc(f.title)+'</h3><p class="win-src">'+esc(f.category)+' · '+esc(f.source)+(f.time?' · '+esc(f.time):'')+'</p><p><strong>What it means:</strong> '+esc(f.explain)+'</p><p><strong>What to do:</strong> '+esc(f.action)+'</p>'+(f.raw?'<details><summary>Original log text</summary><pre>'+esc(f.raw)+'</pre></details>':'')+'</div>').join(''):'<p>No MIDI- or USB-related errors were found in the scanned logs. That does not rule out a device fault; it means Windows itself did not log one.</p>')+'</article>');
  if(a.devices.length)out.push('<article class="panel"><h2>MIDI / USB audio devices known to Windows</h2><div class="compact-table">'+a.devices.map(d=>'<div class="compact-row"><strong>'+esc(d.name||'Unknown')+'</strong><small>'+(d.errorCode?'Code '+d.errorCode+' — '+esc(d.problem?.title||''):'Working')+(d.driver?' · driver '+esc(d.driver.version||'?')+' ('+esc(d.driver.provider||'?')+', '+esc(d.driver.date||'?')+(d.driver.signed===false?', UNSIGNED':'')+')':'')+'</small><span>'+esc(d.class||'')+'</span></div>').join('')+'</div></article>');
  if(a.logs.length)out.push('<article class="panel"><h2>Log entries read</h2>'+a.logs.map(l=>'<div class="win-finding"><p class="win-src">'+esc(l.name)+(l.time?' · '+esc(l.time):'')+'</p><p>'+esc(l.summary)+'</p>'+(l.detail?'<pre>'+esc(l.detail)+'</pre>':'')+(l.action?'<p><strong>What to do:</strong> '+esc(l.action)+'</p>':'')+'</div>').join('')+'</article>');
 }
 for(const l of state.logAnalyses)out.push('<article class="panel"><h2>'+esc(l.name)+'</h2><p>'+esc(l.summary)+'</p>'+(l.findings.length?l.findings.map(f=>'<div class="win-finding"><span class="tag">'+esc(f.severity)+'</span><h3>'+esc(f.title)+'</h3><p><strong>What it means:</strong> '+esc(f.explain)+'</p><p><strong>What to do:</strong> '+esc(f.action)+'</p></div>').join(''):'<p>Nothing MIDI/USB-related stood out in this file.</p>')+'</article>');
 const html=out.join('');if(html!==renderWin.last){renderWin.last=html;els.winResults.innerHTML=html}
}
async function importWinFile(){
 const file=els.winImport.files?.[0];if(!file)return;els.winImport.value='';
 try{
  if(/\.evtx$/i.test(file.name))throw new Error('.evtx is a binary format. In Event Viewer use Save All Events As… > CSV or text, or use the PowerShell scan.');
  if(file.size>8*1024*1024)throw new Error('File is larger than 8 MB; import the last part of the log.');
  const text=await file.text();
  if(/\.json$/i.test(file.name)||text.trimStart().startsWith('{')){const obj=JSON.parse(text.replace(/^\uFEFF/,''));if(!obj||typeof obj!=='object'||(!obj.events&&!obj.devices&&!obj.setupapi))throw new Error('Not a MIDItest Windows scan file.');applyScan(obj);els.winStatus.textContent='Imported scan from '+file.name+'.'}
  else{const r=analyzeLogText(file.name,text);state.logAnalyses.push({name:file.name,type:r.type,summary:r.summary,findings:r.findings});if(state.logAnalyses.length>10)state.logAnalyses.shift();renderWin();els.winStatus.textContent='Explained '+file.name+' ('+r.type+').'}
 }catch(e){els.winStatus.textContent='Could not import: '+(e?.message||e)}
}
async function copyScanScript(){
 try{const text=await (await fetch('./winscan.ps1')).text();
  await navigator.clipboard.writeText(text.trimEnd()+' | Set-Content -Encoding UTF8 "$env:USERPROFILE\\Desktop\\miditest-windows-scan.json"\nWrite-Host "Saved miditest-windows-scan.json to your Desktop. Import it in MIDItest > Windows Logs."\n');
  els.winStatus.textContent='PowerShell scan copied. Paste it into a PowerShell window on the Windows PC and press Enter (read-only; it saves miditest-windows-scan.json to the Desktop).'}
 catch{els.winStatus.textContent='Could not copy the script (clipboard unavailable). Open winscan.ps1 from the project instead.'}
}
els.runBurst.onclick=runBurst;els.winScan.onclick=()=>runWinScan('manual request');els.winCopyScript.onclick=copyScanScript;els.winImport.onchange=importWinFile;
if(!desktop||desktop.platform!=='win32'){els.winScan.disabled=true;els.winScan.title='Live scanning is available in the Windows desktop app. Use Copy PowerShell scan in a browser.'}

$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',String(x===b))});$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===b.dataset.view));if(b.dataset.view==='monitorView')rebuildMonitor();renderAll(false)});
els.connect.onclick=()=>requestMidi(false);els.enableSysex.onclick=()=>requestMidi(true);els.input.onchange=bindInput;els.output.onchange=bindOutput;els.pause.onclick=()=>{paused=!paused;els.pause.textContent=paused?'Resume':'Pause';if(!paused)rebuildMonitor()};els.clear.onclick=()=>resetState(true);els.clearLog.onclick=()=>els.monitor.innerHTML='';[els.search,els.deviceFilter,els.channelFilter,els.typeFilter,els.displayMode].forEach(x=>x.addEventListener('input',rebuildMonitor));
els.guided.onclick=startGuided;els.guidedBack.onclick=()=>changeGuided(-1);els.guidedNext.onclick=()=>changeGuided(1);els.guidedSkip.onclick=skipGuided;els.guidedEnd.onclick=endGuided;els.helpBtn.onclick=()=>els.helpDialog.showModal();const selectControl=e=>{const n=e.target.closest('[data-control]');if(!n||n.dataset.control===selectedControl)return;selectedControl=n.dataset.control;renderControls()};els.controls.addEventListener('pointerdown',selectControl);els.controls.addEventListener('click',selectControl);els.isolateControl.onclick=()=>{if(!selectedControl)return;state.cc.set(selectedControl,[]);state.ccTimes.set(selectedControl,[]);renderAll(true);setStatus('Capture reset for '+selectedControl+'. Move the control now.','connected')};els.applyExpected.onclick=()=>{let low=els.expectedLow.value===''?null:clamp(els.expectedLow.value,0,127),high=els.expectedHigh.value===''?null:clamp(els.expectedHigh.value,0,127),count=els.expectedCount.value===''?null:clamp(els.expectedCount.value,1,128);if(low!==null&&high===null&&count!==null)high=Math.min(127,low+count-1);if(high!==null&&low===null&&count!==null)low=Math.max(0,high-count+1);state.expected={low,high,count};renderAll(true)};
els.noteOn.onclick=()=>sendNote(true);els.noteOff.onclick=()=>sendNote(false);els.sendCc.onclick=sendCc;els.sendProgram.onclick=sendProgram;els.sendPitch.onclick=sendPitch;els.panicChannel.onclick=()=>panic([outChannel()]);els.panicAll.onclick=()=>panic([...Array(16).keys()]);els.runLoopback.onclick=runLoopback;
els.addMapping.onclick=()=>{if(!lastDecoded)return;const s=lastDecoded.kind==='cc'?controlStats(state.cc.get(lastDecoded.channel+':'+lastDecoded.a)||[]):null;state.mappings.push({message:lastDecoded.label+' / Ch '+(lastDecoded.channel??'—')+(s?.count?' / range '+s.min+'-'+s.max:''),label:els.mappingLabel.value.trim()||'Unlabeled'});els.mappingLabel.value='';renderMappings();renderReport()};
els.copyLearn.onclick=async()=>{try{await navigator.clipboard.writeText(els.learn.textContent);setStatus('MIDI Learn summary copied.','connected')}catch{setStatus('Clipboard access unavailable.','attention')}};
els.exportCaptureJson.onclick=()=>download('miditest-capture.json',JSON.stringify(state.events,null,2),'application/json');els.exportCaptureCsv.onclick=()=>download('miditest-capture.csv',csv([['timestamp','wallTime','device','channel','type','message','value','decimal','hex'],...state.events.map(e=>[e.t,e.wallTime,e.device,e.channel,e.kind,e.label,e.value,e.decimal,e.hex])]),'text/csv');els.exportMappingJson.onclick=()=>download('miditest-mappings.json',JSON.stringify(state.mappings,null,2),'application/json');els.exportMappingCsv.onclick=()=>download('miditest-mappings.csv',csv([['message','label'],...state.mappings.map(m=>[m.message,m.label])]),'text/csv');els.printMapping.onclick=()=>{$('[data-view="mappingView"]').click();window.print()};
els.saveBaseline.onclick=()=>{localStorage.setItem('miditest-baseline-v2',JSON.stringify(buildReport()));setStatus('Baseline saved locally in this browser.','connected')};els.compareBaseline.onclick=()=>{const raw=localStorage.getItem('miditest-baseline-v2');if(!raw){setStatus('No saved baseline found.','attention');return}try{const obj=JSON.parse(raw);if(validateReport(obj))throw new Error();state.importedReport=obj;renderReport();setStatus('Baseline comparison loaded.','connected')}catch{setStatus('Saved baseline is invalid.','attention')}};els.importReport.onchange=async()=>{const file=els.importReport.files?.[0];if(!file)return;try{const obj=JSON.parse(await file.text());const problem=validateReport(obj);if(problem)throw new Error(problem);state.importedReport=obj;renderReport();setStatus('Prior report imported for comparison.','connected')}catch(e){setStatus('Could not import report: '+e.message,'attention')}};els.clearLocal.onclick=()=>{for(const k of Object.keys(localStorage))if(k.startsWith('miditest'))localStorage.removeItem(k);state.importedReport=null;setStatus('MIDItest local data cleared.','connected');renderReport()};
els.exportReport.onclick=()=>download('miditest-report.json',JSON.stringify(buildReport(),null,2),'application/json');els.exportReportCsv.onclick=()=>{const r=buildReport(),rows=[['field','value'],['device',r.device],['durationMs',r.durationMs],['eventCount',r.eventCount],['keys',r.keys.join(' ')],['channels',r.channels.join(' ')],['disconnects',r.disconnects],['velocityMin',r.velocity.min],['velocityMax',r.velocity.max],['pitchMin',r.pitch.min],['pitchMax',r.pitch.max],['clockBpm',r.clock.bpm],['latencyMedian',r.latency.median],...r.observations.map((o,i)=>['finding'+(i+1),o.text])];download('miditest-report.csv',csv(rows),'text/csv')};els.printReport.onclick=()=>{$('[data-view="reportView"]').click();renderReport();window.print()};
function saveSettings(){localStorage.setItem('miditest-settings-v2',JSON.stringify({preset:els.preset.value,typeFilter:els.typeFilter.value,displayMode:els.displayMode.value,autoscroll:els.autoscroll.checked}))}
function loadSettings(){try{const s=JSON.parse(localStorage.getItem('miditest-settings-v2')||'{}');if(s.preset)els.preset.value=s.preset;if(s.typeFilter!==undefined)els.typeFilter.value=s.typeFilter;if(s.displayMode)els.displayMode.value=s.displayMode;if(s.autoscroll!==undefined)els.autoscroll.checked=!!s.autoscroll}catch{}}
[els.preset,els.typeFilter,els.displayMode,els.autoscroll].forEach(x=>x.addEventListener('change',saveSettings));loadSettings();setInterval(()=>els.elapsed.textContent=formatElapsed(Date.now()-state.started),1000);
setStatus(navigator.requestMIDIAccess?'Web MIDI is available. Enable MIDI to begin hardware diagnostics.':'Web MIDI is unavailable in this browser; documentation and interface remain available.',navigator.requestMIDIAccess?'':'attention');if(!navigator.requestMIDIAccess){els.connect.disabled=true;els.enableSysex.disabled=true}guidedRender();resetState(true);updateHardwareControls();
// Feature modules (replay, checklists, profiles, charts, SysEx, active tests, clock generator, multi-device, UMP, glossary, report export) attach through this small API.
import('./features.js').then(m=>m.initFeatures({state,els,$,$$,esc,clamp,metric,stat,histogram,download,csv,setStatus,scheduleRender,renderAll,buildReport,testResults,send,outChannel,portName,primaryPitch,resetState,rebuildMonitor,updateHardwareControls,viewRenderers,onMidi,applyScan,getInput:()=>currentInput,getOutput:()=>currentOutput,getAccess:()=>access,onIngest:fn=>ingestHooks.push(fn),extendReport:fn=>reportExtensions.push(fn),setBulk:v=>{bulk=!!v}})).catch(e=>{console.error('features failed to load',e);setStatus('Some optional features failed to load: '+(e?.message||e),'attention')});
