import {decodeMessage,noteName,controlStats,pitchStats,clockBpm,classifyEncoder,messageRate,reportSummary} from './midi-core.js';
const $=s=>document.querySelector(s); const els={connect:$('#connect'),guided:$('#guided'),clear:$('#clear'),support:$('#support'),input:$('#input'),output:$('#output'),typeFilter:$('#typeFilter'),pause:$('#pause'),summary:$('#summary'),monitor:$('#monitor'),messageStats:$('#messageStats'),channels:$('#channels'),controls:$('#controls'),keySummary:$('#keySummary'),keyboard:$('#keyboard'),held:$('#held'),bendNeedle:$('#bendNeedle'),pitchStats:$('#pitchStats'),clock:$('#clock'),learn:$('#learn'),mappingLabel:$('#mappingLabel'),addMapping:$('#addMapping'),mappingRows:$('#mappingRows'),outChannel:$('#outChannel'),outNote:$('#outNote'),outVelocity:$('#outVelocity'),noteOn:$('#noteOn'),noteOff:$('#noteOff'),panic:$('#panic'),connections:$('#connections'),saveBaseline:$('#saveBaseline'),compareBaseline:$('#compareBaseline'),exportReport:$('#exportReport'),reportPreview:$('#reportPreview'),clearLog:$('#clearLog')};
let access=null,currentInput=null,currentOutput=null,lastDecoded=null;
const state={device:'',started:null,events:[],timestamps:[],keys:new Set(),held:new Set(),channels:new Set(),messageCounts:{},cc:new Map(),pitchValues:[],clockTimes:[],connections:[],disconnects:0,mappings:[]};

function resetState(){state.started=Date.now();state.events=[];state.timestamps=[];state.keys=new Set();state.held=new Set();state.channels=new Set();state.messageCounts={};state.cc=new Map();state.pitchValues=[];state.clockTimes=[];state.connections=[];state.disconnects=0;lastDecoded=null;renderAll();}
function logConnection(text){const line=`${new Date().toLocaleTimeString()}  ${text}`;state.connections.unshift(line);state.connections=state.connections.slice(0,50);els.connections.textContent=state.connections.join('\n');}
function fillPorts(){if(!access)return;const inVal=els.input.value,outVal=els.output.value;els.input.innerHTML='<option value="">No input selected</option>'+[...access.inputs.values()].map(p=>`<option value="${p.id}">${p.name||p.manufacturer||p.id}</option>`).join('');els.output.innerHTML='<option value="">No output selected</option>'+[...access.outputs.values()].map(p=>`<option value="${p.id}">${p.name||p.manufacturer||p.id}</option>`).join('');if([...access.inputs.keys()].includes(inVal))els.input.value=inVal;else if(access.inputs.size===1)els.input.value=[...access.inputs.keys()][0];if([...access.outputs.keys()].includes(outVal))els.output.value=outVal;else if(access.outputs.size===1)els.output.value=[...access.outputs.keys()][0];bindInput();bindOutput();}
function bindInput(){if(currentInput)currentInput.onmidimessage=null;currentInput=access?.inputs.get(els.input.value)||null;if(currentInput){currentInput.onmidimessage=onMidi;state.device=currentInput.name||currentInput.id;logConnection(`Input selected: ${state.device}`)}}
function bindOutput(){currentOutput=access?.outputs.get(els.output.value)||null;if(currentOutput)logConnection(`Output selected: ${currentOutput.name||currentOutput.id}`)}
async function connect(){if(!navigator.requestMIDIAccess){els.support.textContent='Web MIDI is not available in this browser. Use a current Chromium-based browser for hardware access.';return}try{access=await navigator.requestMIDIAccess({sysex:false});access.onstatechange=e=>{const p=e.port;logConnection(`${p.type} ${p.name||p.id}: ${p.state}/${p.connection}`);if(p.state==='disconnected')state.disconnects++;fillPorts();renderAll()};fillPorts();els.support.textContent='MIDI access enabled. Select an input and move or play controls.';els.connect.textContent='MIDI Enabled';els.connect.disabled=true;resetState()}catch(e){els.support.textContent=`MIDI permission was not granted: ${e.message}`}}

function onMidi(ev){const now=performance.now(),d=decodeMessage(ev.data);lastDecoded=d;state.events.push({t:now,...d});if(state.events.length>1500)state.events.shift();state.timestamps.push(now);if(state.timestamps.length>3000)state.timestamps.shift();state.messageCounts[d.kind]=(state.messageCounts[d.kind]||0)+1;if(d.channel)state.channels.add(d.channel);if(d.kind==='noteon'){state.keys.add(d.a);state.held.add(d.a)}if(d.kind==='noteoff')state.held.delete(d.a);if(d.kind==='cc'){const k=`${d.channel}:${d.a}`;if(!state.cc.has(k))state.cc.set(k,[]);const arr=state.cc.get(k);arr.push(d.value);if(arr.length>500)arr.shift()}if(d.kind==='pitchbend'){state.pitchValues.push(d.value);if(state.pitchValues.length>500)state.pitchValues.shift()}if(d.kind==='clock'){state.clockTimes.push(now);if(state.clockTimes.length>240)state.clockTimes.shift()}if(!els.pause.checked)prependMessage(d,now);renderAll()}
function prependMessage(d,now){if(els.typeFilter.value&&d.kind!==els.typeFilter.value)return;const row=document.createElement('div');row.className='msg';row.innerHTML=`<span>${(now/1000).toFixed(3)}</span><span>${d.channel||'—'}</span><span>${d.label}</span><span class="val">${d.value}</span><span class="raw">${d.hex}</span>`;els.monitor.prepend(row);while(els.monitor.children.length>300)els.monitor.lastChild.remove()}
function stat(label,value){return `<div class="stat"><strong>${value}</strong><span>${label}</span></div>`}
function renderSummary(){const rate=messageRate(state.timestamps);els.summary.innerHTML=[stat('Events',state.events.length.toLocaleString()),stat('Msg/sec',rate.toFixed(0)),stat('Keys seen',state.keys.size),stat('CCs seen',state.cc.size),stat('Channels',state.channels.size),stat('Disconnects',state.disconnects)].join('')}
function meterRows(entries){const max=Math.max(1,...entries.map(x=>x[1]));return entries.map(([k,v])=>`<div class="meter"><span>${k}</span><div class="track"><div class="fill" style="width:${v/max*100}%"></div></div><b>${v}</b></div>`).join('')||'<p class="muted">No activity yet.</p>'}
function renderMessages(){els.messageStats.innerHTML=meterRows(Object.entries(state.messageCounts).sort((a,b)=>b[1]-a[1]));const ch=[...state.channels].sort((a,b)=>a-b).map(c=>[ `Channel ${c}`, state.events.filter(e=>e.channel===c).length]);els.channels.innerHTML=meterRows(ch)}
function renderControls(){const items=[...state.cc.entries()].sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true}));els.controls.innerHTML=items.length?items.map(([k,vals])=>{const s=controlStats(vals),enc=classifyEncoder(vals);return `<div class="control"><div class="control-head"><strong>Ch ${k.split(':')[0]} · CC ${k.split(':')[1]}</strong><span>${vals.at(-1)}</span></div><div class="control-meta">range ${s.min}–${s.max} · ${s.unique} values · jitter ${s.jitter} · jumps ${s.jumps} · ${enc}</div></div>`}).join(''):'<p class="muted">Move a knob, slider, wheel or pedal to begin profiling.</p>'}
function renderKeyboard(){const seen=[...state.keys].sort((a,b)=>a-b);els.keySummary.textContent=seen.length?`${seen.length} notes observed · ${noteName(seen[0])} to ${noteName(seen.at(-1))}`:'No notes observed.';const low=seen.length?Math.max(0,seen[0]-2):48, high=seen.length?Math.min(127,Math.max(seen.at(-1)+2,low+23)):71;let html='';for(let n=low;n<=high;n++){const black=[1,3,6,8,10].includes(n%12);html+=`<div class="key ${black?'black':''} ${state.keys.has(n)?'seen':''} ${state.held.has(n)?'held':''}" title="${noteName(n)}">${noteName(n)}</div>`}els.keyboard.innerHTML=html;els.held.innerHTML=[...state.held].sort((a,b)=>a-b).map(n=>`<span>${noteName(n)}</span>`).join('')||'<span>None</span>'}
function renderPitch(){const s=pitchStats(state.pitchValues),cur=state.pitchValues.at(-1)||0;els.bendNeedle.style.left=`${50+(cur/8192)*50}%`;els.pitchStats.innerHTML=s.count?`<p>Observed ${s.min} to ${s.max}</p><p>Near-center mean ${s.center??'—'} · spread ${s.centerSpread??'—'}</p>`:'<p class="muted">Move pitch bend to begin.</p>';const bpm=clockBpm(state.clockTimes);els.clock.textContent=bpm?`Measured ${bpm.toFixed(2)} BPM from incoming MIDI clock.`:'No stable clock observed.'}
function renderLearn(){if(!lastDecoded){els.learn.textContent='Waiting for a message…';return}els.learn.textContent=`${lastDecoded.label} · Ch ${lastDecoded.channel||'—'} · value ${lastDecoded.value} · ${lastDecoded.hex}`}
function renderMappings(){els.mappingRows.innerHTML=state.mappings.map((m,i)=>`<tr><td>${m.message}</td><td>${m.label}</td><td><button data-remove="${i}">×</button></td></tr>`).join('');els.mappingRows.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.mappings.splice(Number(b.dataset.remove),1);renderMappings()})}
function buildReport(){const controls={};for(const [k,v] of state.cc)controls[k]={...controlStats(v),encoder:classifyEncoder(v),last:v.at(-1)};const report=reportSummary({...state,controls,pitch:pitchStats(state.pitchValues)});report.connectionLog=state.connections;report.mappings=state.mappings;report.clockBpm=clockBpm(state.clockTimes);report.observations=[];for(const [k,c] of Object.entries(controls)){if(c.range<110)report.observations.push(`${k}: limited range observed (${c.min}–${c.max})`);if(c.jitter>2)report.observations.push(`${k}: elevated stationary variation observed (${c.jitter})`);if(c.jumps>0)report.observations.push(`${k}: ${c.jumps} sudden value jumps observed`)}if(state.disconnects)report.observations.push(`${state.disconnects} MIDI disconnect event(s) observed`);return report}
function renderReport(){els.reportPreview.textContent=JSON.stringify(buildReport(),null,2)}
function renderAll(){renderSummary();renderMessages();renderControls();renderKeyboard();renderPitch();renderLearn();renderMappings();renderReport()}
function send(bytes){if(!currentOutput){alert('Select a MIDI output first.');return}currentOutput.send(bytes)}
function note(on){const ch=Math.max(1,Math.min(16,Number(els.outChannel.value)||1))-1,n=Math.max(0,Math.min(127,Number(els.outNote.value)||60)),v=Math.max(0,Math.min(127,Number(els.outVelocity.value)||100));send([(on?0x90:0x80)|ch,n,on?v:0])}
function panic(){if(!currentOutput){alert('Select a MIDI output first.');return}for(let ch=0;ch<16;ch++){send([0xB0|ch,120,0]);send([0xB0|ch,121,0]);send([0xB0|ch,123,0])}}
function downloadReport(){const blob=new Blob([JSON.stringify(buildReport(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='miditest-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function guided(){resetState();els.guided.textContent='Guided Test Running';els.support.textContent='Press every key once, move every knob/slider through full travel, test pitch/mod wheels, buttons and pedals. Export the report when finished.'}

els.connect.onclick=connect;els.input.onchange=bindInput;els.output.onchange=bindOutput;els.clear.onclick=resetState;els.guided.onclick=guided;els.clearLog.onclick=()=>els.monitor.innerHTML='';els.typeFilter.onchange=()=>{els.monitor.innerHTML='';for(const e of state.events.slice().reverse())prependMessage(e,e.t)};els.addMapping.onclick=()=>{if(!lastDecoded)return;state.mappings.push({message:`${lastDecoded.label} / Ch ${lastDecoded.channel||'—'}`,label:els.mappingLabel.value.trim()||'Unlabeled'});els.mappingLabel.value='';renderMappings();renderReport()};els.noteOn.onclick=()=>note(true);els.noteOff.onclick=()=>note(false);els.panic.onclick=panic;els.exportReport.onclick=downloadReport;els.saveBaseline.onclick=()=>{localStorage.setItem('miditest-baseline',JSON.stringify(buildReport()));els.support.textContent='Baseline saved locally in this browser.'};els.compareBaseline.onclick=()=>{const raw=localStorage.getItem('miditest-baseline');if(!raw){els.support.textContent='No saved baseline found.';return}const old=JSON.parse(raw),cur=buildReport();els.reportPreview.textContent=JSON.stringify({baseline:{eventCount:old.eventCount,disconnects:old.disconnects,keys:old.keys?.length||0,controls:Object.keys(old.controls||{}).length},current:{eventCount:cur.eventCount,disconnects:cur.disconnects,keys:cur.keys.length,controls:Object.keys(cur.controls).length}},null,2)};
els.support.textContent=navigator.requestMIDIAccess?'Web MIDI is available. Click Enable MIDI to grant hardware access.':'Web MIDI is unavailable in this browser.';resetState();
