import {decodeMessage,noteName,controlStats,pitchStats,clockBpm,classifyEncoder,messageRate,reportSummary,velocityHistogram,detectChatter,eventsToCsv,interval} from './midi-core.js';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ids=['connect','guided','clear','support','input','output','typeFilter','pause','hideNoise','summary','monitor','messageStats','channels','controls','keySummary','keyboard','held','bendNeedle','pitchStats','clock','learn','mappingLabel','addMapping','mappingRows','outChannel','outNote','outVelocity','noteOn','noteOff','panic','connections','saveBaseline','compareBaseline','exportReport','reportPreview','clearLog','exportCsv','checklist','velHist'];
const els=Object.fromEntries(ids.map(i=>[i,$('#'+i)]));
const NOISE=new Set(['clock','active']);
let access=null,currentInputs=[],currentOutput=null,lastDecoded=null,dirty=false,guidedOn=false;
const state={device:'',started:null,events:[],timestamps:[],keys:new Set(),held:new Set(),lastVel:new Map(),channels:new Set(),messageCounts:{},cc:new Map(),pitchValues:[],clockTimes:[],connections:[],disconnects:0,mappings:[],velocityValues:[],sustainValues:[]};
function resetState(){Object.assign(state,{started:Date.now(),events:[],timestamps:[],keys:new Set(),held:new Set(),lastVel:new Map(),channels:new Set(),messageCounts:{},cc:new Map(),pitchValues:[],clockTimes:[],connections:[],disconnects:0,velocityValues:[],sustainValues:[]});lastDecoded=null;els.monitor.innerHTML='';els.connections.textContent='';renderAll()}
function logConnection(t){state.connections.unshift(`${new Date().toLocaleTimeString()}  ${t}`);state.connections.length=Math.min(50,state.connections.length);els.connections.textContent=state.connections.join('\n')}
function say(t){els.support.textContent=t}
function fillPorts(){if(!access)return;const iv=els.input.value,ov=els.output.value,opt=(m,none)=>`<option value="">${none}</option>`+[...m.values()].map(p=>`<option value="${esc(p.id)}">${esc(p.name||p.manufacturer||p.id)}</option>`).join('');
els.input.innerHTML=(access.inputs.size>1?'<option value="*">All inputs</option>':'')+opt(access.inputs,'No input selected');els.output.innerHTML=opt(access.outputs,'No output selected');
const pick=(sel,m,prev)=>{if(prev==='*'&&m.size>1||m.has(prev))sel.value=prev;else if(m.size===1)sel.value=[...m.keys()][0];else if(m.size>1&&sel===els.input)sel.value='*'};pick(els.input,access.inputs,iv);pick(els.output,access.outputs,ov);bindInput();bindOutput()}
function bindInput(){currentInputs.forEach(p=>p.onmidimessage=null);const v=els.input.value;currentInputs=v==='*'?[...access.inputs.values()]:[access?.inputs.get(v)].filter(Boolean);currentInputs.forEach(p=>p.onmidimessage=onMidi);state.device=currentInputs.map(p=>p.name||p.id).join(', ');if(currentInputs.length)logConnection(`Listening: ${state.device}`)}
function bindOutput(){currentOutput=access?.outputs.get(els.output.value)||null;if(currentOutput)logConnection(`Output: ${currentOutput.name||currentOutput.id}`)}
async function connect(){if(!navigator.requestMIDIAccess){say('Web MIDI is not available in this browser. Use a current Chromium-based browser (Chrome, Edge, Opera) for hardware access.');return}
try{access=await navigator.requestMIDIAccess({sysex:false});access.onstatechange=e=>{const p=e.port;logConnection(`${p.type} ${p.name||p.id}: ${p.state}/${p.connection}`);if(p.state==='disconnected')state.disconnects++;fillPorts();renderAll()};fillPorts();say(access.inputs.size?'MIDI enabled. Play or move something.':'MIDI enabled, but no input devices were found. Plug one in — it will appear automatically.');els.connect.textContent='MIDI enabled';els.connect.disabled=true;resetState()}catch(e){say(`MIDI permission was not granted: ${e.message}`)}}
const push=(a,v,max)=>{a.push(v);if(a.length>max)a.shift()};
function onMidi(ev){const now=performance.now(),d=decodeMessage(ev.data);if(d.kind==='active'){state.messageCounts.active=(state.messageCounts.active||0)+1;return schedule()}
lastDecoded=NOISE.has(d.kind)?lastDecoded:d;state.events.push({t:now,...d});if(state.events.length>3000)state.events.shift();push(state.timestamps,now,3000);state.messageCounts[d.kind]=(state.messageCounts[d.kind]||0)+1;if(d.channel)state.channels.add(d.channel);
if(d.kind==='noteon'){state.keys.add(d.a);state.held.add(d.a);state.lastVel.set(d.a,d.b);push(state.velocityValues,d.b,2000)}else if(d.kind==='noteoff')state.held.delete(d.a);
else if(d.kind==='cc'){const k=`${d.channel}:${d.a}`;if(!state.cc.has(k))state.cc.set(k,[]);push(state.cc.get(k),d.value,500);if(d.a===64)push(state.sustainValues,d.value,500);if(d.a===123||d.a===120)state.held.clear()}
else if(d.kind==='pitchbend')push(state.pitchValues,d.value,500);else if(d.kind==='clock')push(state.clockTimes,now,240);
if(!els.pause.checked)prependMessage(d,now);schedule()}
function schedule(){if(!dirty){dirty=true;requestAnimationFrame(()=>{dirty=false;renderAll()})}}
function visible(d){if(els.hideNoise.checked&&NOISE.has(d.kind)&&els.typeFilter.value!==d.kind)return false;const f=els.typeFilter.value;return !f||d.kind===f||(f==='noteon'&&0)}
function prependMessage(d,now){if(!visible(d))return;const row=document.createElement('div');row.className=`msg ${d.kind}`;row.innerHTML=`<span>${(now/1000).toFixed(3)}</span><span>${d.channel||'—'}</span><span>${esc(d.label)}</span><span class="val">${esc(d.value)}</span><span class="raw">${esc(d.hex)}</span>`;els.monitor.prepend(row);while(els.monitor.children.length>300)els.monitor.lastChild.remove()}
const stat=(l,v)=>`<div class="stat"><strong>${esc(v)}</strong><span>${esc(l)}</span></div>`;
function renderSummary(){const vel=state.velocityValues,iv=interval(state.clockTimes);els.summary.innerHTML=[stat('Events',state.events.length.toLocaleString()),stat('Msg/sec',messageRate(state.timestamps,1000,performance.now()).toFixed(0)),stat('Keys seen',state.keys.size),stat('Velocity range',vel.length?`${Math.min(...vel)}–${Math.max(...vel)}`:'—'),stat('CCs seen',state.cc.size),stat('Channels',state.channels.size),stat('Key chatter',detectChatter(state.events)),stat('Disconnects',state.disconnects)].join('')}
function meterRows(e){const max=Math.max(1,...e.map(x=>x[1]));return e.map(([k,v])=>`<div class="meter"><span>${esc(k)}</span><div class="track"><div class="fill" style="width:${v/max*100}%"></div></div><b>${v}</b></div>`).join('')||'<p class="muted">No activity yet.</p>'}
function renderMessages(){els.messageStats.innerHTML=meterRows(Object.entries(state.messageCounts).sort((a,b)=>b[1]-a[1]));const c={};for(const e of state.events)if(e.channel)c[e.channel]=(c[e.channel]||0)+1;els.channels.innerHTML=Object.keys(c).length?meterRows(Object.entries(c).map(([k,v])=>[`Channel ${k}`,v])):''}
function renderControls(){const items=[...state.cc.entries()].sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true}));els.controls.innerHTML=items.length?items.map(([k,vals])=>{const s=controlStats(vals),enc=classifyEncoder(vals),[ch,cc]=k.split(':'),name=cc==='64'?'Sustain pedal':cc==='1'?'Mod wheel':`CC ${cc}`,last=vals.at(-1);return `<div class="control"><div class="control-head"><strong>Ch ${esc(ch)} · ${name}</strong><span>${esc(last)}</span></div><div class="track"><div class="fill" style="width:${Math.max(0,Math.min(100,last/127*100))}%"></div></div><div class="control-meta">range ${s.min}–${s.max} · ${s.unique} values · jitter ${s.jitter} · jumps ${s.jumps} · ${esc(enc)}</div></div>`}).join(''):'<p class="muted">Move a knob, slider, wheel or pedal to begin profiling.</p>'}
const BLACK=new Set([1,3,6,8,10]);
function renderKeyboard(){const seen=[...state.keys].sort((a,b)=>a-b);els.keySummary.textContent=seen.length?`${seen.length} tested · ${noteName(seen[0])}–${noteName(seen.at(-1))}`:'no notes yet';const lo=21,hi=108;let whites=0;for(let n=lo;n<=hi;n++)if(!BLACK.has(n%12))whites++;const w=100/whites;let wi=0,html='';for(let n=lo;n<=hi;n++){const cls=`${state.keys.has(n)?'seen':''} ${state.held.has(n)?'held':''}`;if(BLACK.has(n%12))html+=`<div class="bk ${cls}" style="left:${wi*w-w*.3}%;width:${w*.6}%" title="${noteName(n)}${state.lastVel.has(n)?' vel '+state.lastVel.get(n):''}"></div>`;else{html+=`<div class="wk ${cls}" style="left:${wi*w}%;width:${w}%" title="${noteName(n)}${state.lastVel.has(n)?' vel '+state.lastVel.get(n):''}"></div>`;wi++}}els.keyboard.innerHTML=html;els.held.innerHTML=[...state.held].sort((a,b)=>a-b).map(n=>`<span>${noteName(n)}</span>`).join('')||'<span>None</span>'}
function renderPitch(){const s=pitchStats(state.pitchValues),cur=state.pitchValues.at(-1)||0;els.bendNeedle.style.left=`${50+(cur/8192)*50}%`;const sus=state.sustainValues.length?controlStats(state.sustainValues):null;const iv=interval(state.timestamps.filter((_,i,a)=>i>a.length-200));els.pitchStats.innerHTML=s.count?`<p class="muted">Observed ${s.min} to ${s.max} · centre ${s.center??'—'} (±${s.centerSpread??'—'})</p>`:'<p class="muted">Move pitch bend to begin.</p>';if(sus)els.pitchStats.innerHTML+=`<p class="muted">Sustain CC64 ${sus.min}–${sus.max}${sus.unique>2?' · half-damper values seen':''}</p>`;const bpm=clockBpm(state.clockTimes);els.clock.textContent=bpm?`${bpm.toFixed(2)} BPM measured from incoming clock.`:'No stable clock observed.'}
function renderHist(){const h=velocityHistogram(state.velocityValues),m=Math.max(1,...h);els.velHist.innerHTML=h.map((v,i)=>`<div style="height:${v/m*100}%" title="${v} hits"><small>${Math.round(i*127/h.length)+1}</small></div>`).join('')}
function checks(){const v=state.velocityValues,all=[...state.cc.entries()],has=cc=>all.filter(([k])=>k.endsWith(':'+cc)).flatMap(([,x])=>x),mod=controlStats(has(1)),sus=has(64),pb=state.pitchValues,chat=detectChatter(state.events);
const knob=all.some(([,x])=>controlStats(x).range>=100);
return [['Play at least 25 different keys',state.keys.size>=25,''],['Soft hit (velocity < 40)',v.some(x=>x<40)],['Hard hit (velocity > 110)',v.some(x=>x>110)],['Pitch bend up and down',pb.some(x=>x>6000)&&pb.some(x=>x<-6000)],['Mod wheel full travel (CC1)',mod.range>=100],['Sustain pedal on and off (CC64)',sus.some(x=>x>=64)&&sus.some(x=>x<64)],['A knob/slider swept full travel',knob],['No key chatter detected',chat===0&&state.keys.size>0,chat?'fail':'']].map(([t,ok,f])=>[t,ok,f==='fail'])}
function renderChecks(){els.checklist.innerHTML=checks().map(([t,ok,fail])=>`<li class="${fail?'fail':ok?'done':''}">${esc(t)}</li>`).join('')}
function renderLearn(){els.learn.textContent=lastDecoded?`${lastDecoded.label} · Ch ${lastDecoded.channel||'—'} · value ${lastDecoded.value} · ${lastDecoded.hex}`:'Waiting for a message…'}
function renderMappings(){els.mappingRows.innerHTML=state.mappings.map((m,i)=>`<tr><td>${esc(m.message)}</td><td>${esc(m.label)}</td><td><button data-remove="${i}" aria-label="Remove">×</button></td></tr>`).join('');els.mappingRows.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.mappings.splice(Number(b.dataset.remove),1);renderMappings();renderReport()})}
function buildReport(){const controls={};for(const [k,v] of state.cc)controls[k]={...controlStats(v),encoder:classifyEncoder(v),last:v.at(-1)};const r=reportSummary({...state,controls,pitch:pitchStats(state.pitchValues)});r.connectionLog=state.connections;r.mappings=state.mappings;r.clockBpm=clockBpm(state.clockTimes);r.velocity=state.velocityValues.length?{min:Math.min(...state.velocityValues),max:Math.max(...state.velocityValues),histogram:velocityHistogram(state.velocityValues),samples:state.velocityValues.length}:null;r.sustain=state.sustainValues.length?controlStats(state.sustainValues):null;r.keyChatter=detectChatter(state.events);r.checklist=Object.fromEntries(checks().map(([t,ok])=>[t,ok]));r.observations=[];
for(const [k,c] of Object.entries(controls)){if(c.encoder.startsWith('Absolute')&&c.range<110)r.observations.push(`${k}: limited range observed (${c.min}–${c.max})`);if(c.jitter>2)r.observations.push(`${k}: elevated stationary variation (${c.jitter})`);if(c.jumps>0)r.observations.push(`${k}: ${c.jumps} sudden value jump(s)`)}
if(r.keyChatter)r.observations.push(`${r.keyChatter} possible key chatter event(s) (re-trigger <40 ms)`);if(state.disconnects)r.observations.push(`${state.disconnects} MIDI disconnect event(s)`);return r}
function renderReport(){if(!comparing)els.reportPreview.textContent=JSON.stringify(buildReport(),null,2)}
let comparing=false;
function renderAll(){renderSummary();renderMessages();renderControls();renderKeyboard();renderPitch();renderHist();renderChecks();renderLearn();renderMappings();renderReport()}
function send(b){if(!currentOutput){say('Select a MIDI output first.');return false}currentOutput.send(b);return true}
function note(on){const c=x=>Math.max(0,Math.min(127,x)),ch=Math.max(1,Math.min(16,Number(els.outChannel.value)||1))-1;send([(on?0x90:0x80)|ch,c(Number(els.outNote.value)||60),on?c(Number(els.outVelocity.value)||100):0])}
function panic(){if(!currentOutput){say('Select a MIDI output first.');return}for(let ch=0;ch<16;ch++){send([0xB0|ch,120,0]);send([0xB0|ch,121,0]);send([0xB0|ch,123,0])}say('Panic sent on all 16 channels.')}
function download(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function compare(){let old;try{old=JSON.parse(localStorage.getItem('miditest-baseline')||'null')}catch{}if(!old){say('No saved baseline found.');return}const cur=buildReport(),n=o=>Object.keys(o||{}).length,row=(k,a,b)=>({[k]:{baseline:a,current:b}});comparing=true;els.reportPreview.textContent=JSON.stringify({...row('events',old.eventCount,cur.eventCount),...row('keysTested',old.keys?.length||0,cur.keys.length),...row('controls',n(old.controls),n(cur.controls)),...row('disconnects',old.disconnects,cur.disconnects),...row('keyChatter',old.keyChatter??0,cur.keyChatter),...row('observations',old.observations?.length??0,cur.observations.length),newObservations:cur.observations.filter(o=>!(old.observations||[]).includes(o))},null,2);say('Baseline comparison shown below. Click Clear session or save/export to return to the live report.')}
els.connect.onclick=connect;els.input.onchange=bindInput;els.output.onchange=bindOutput;els.clear.onclick=()=>{comparing=false;resetState()};
els.guided.onclick=()=>{comparing=false;resetState();say('Guided test: press keys soft and hard, sweep every knob, move pitch/mod wheels and pedals. Watch the checklist, then export the report.');$('#checklist').scrollIntoView({behavior:'smooth',block:'center'})};
els.clearLog.onclick=()=>els.monitor.innerHTML='';
const refilter=()=>{els.monitor.innerHTML='';for(const e of state.events.slice(-300))prependMessage(e,e.t)};els.typeFilter.onchange=refilter;els.hideNoise.onchange=refilter;
els.addMapping.onclick=()=>{if(!lastDecoded){say('Touch a control first.');return}state.mappings.push({message:`${lastDecoded.label} / Ch ${lastDecoded.channel||'—'}`,label:els.mappingLabel.value.trim()||'Unlabeled'});els.mappingLabel.value='';renderMappings();renderReport()};
els.noteOn.onclick=()=>note(true);els.noteOff.onclick=()=>note(false);els.panic.onclick=panic;
els.exportReport.onclick=()=>{comparing=false;renderReport();download(JSON.stringify(buildReport(),null,2),'miditest-report.json','application/json')};
els.exportCsv.onclick=()=>state.events.length?download(eventsToCsv(state.events),'miditest-events.csv','text/csv'):say('No events to export yet.');
els.saveBaseline.onclick=()=>{try{localStorage.setItem('miditest-baseline',JSON.stringify(buildReport()));say('Baseline saved locally in this browser.')}catch{say('Could not save baseline (browser storage blocked).')}};
els.compareBaseline.onclick=compare;
say(navigator.requestMIDIAccess?'Web MIDI is available. Click “Enable MIDI” to grant hardware access.':'Web MIDI is unavailable in this browser. Try Chrome, Edge or Opera.');resetState();setInterval(()=>{if(state.timestamps.length)schedule()},1000);
