export function noteName(n){const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];return `${names[n%12]}${Math.floor(n/12)-1}`}
export function decodeMessage(data){const d=[...data],status=d[0]||0,type=status&0xf0,ch=(status&0x0f)+1,a=d[1]??0,b=d[2]??0;let kind='system',label='System';if(type===0x80||(type===0x90&&b===0)){kind='noteoff';label=`Note Off ${noteName(a)}`;}else if(type===0x90){kind='noteon';label=`Note On ${noteName(a)}`;}else if(type===0xA0){kind='polyaftertouch';label=`Poly Aftertouch ${noteName(a)}`;}else if(type===0xB0){kind='cc';label=`CC ${a}`;}else if(type===0xC0){kind='program';label=`Program ${a}`;}else if(type===0xD0){kind='aftertouch';label='Channel Aftertouch';}else if(type===0xE0){kind='pitchbend';label='Pitch Bend';}else if(status===0xF8){kind='clock';label='MIDI Clock';}else if(status===0xFA){kind='start';label='Start';}else if(status===0xFB){kind='continue';label='Continue';}else if(status===0xFC){kind='stop';label='Stop';}else if(status===0xFE){kind='active';label='Active Sense';}else if(status===0xFF){kind='reset';label='System Reset';}
 const value=kind==='pitchbend'?((b<<7)|a)-8192:(d.length>2?b:a);return {status,type,channel:type>=0x80&&type<=0xE0?ch:null,a,b,value,kind,label,raw:d,hex:d.map(x=>x.toString(16).padStart(2,'0').toUpperCase()).join(' ')} }
export function controlStats(values=[]){if(!values.length)return {count:0,min:null,max:null,range:0,unique:0,jitter:0,jumps:0,reversals:0};const min=Math.min(...values),max=Math.max(...values);let jumps=0,reversals=0,lastDir=0;for(let i=1;i<values.length;i++){const delta=values[i]-values[i-1];if(Math.abs(delta)>12)jumps++;const dir=Math.sign(delta);if(dir&&lastDir&&dir!==lastDir)reversals++;if(dir)lastDir=dir;}const tail=values.slice(-Math.min(20,values.length));const mean=tail.reduce((a,b)=>a+b,0)/tail.length;const jitter=Math.sqrt(tail.reduce((a,b)=>a+(b-mean)**2,0)/tail.length);return {count:values.length,min,max,range:max-min,unique:new Set(values).size,jitter:Number(jitter.toFixed(2)),jumps,reversals}}
export function pitchStats(values=[]){if(!values.length)return {count:0,min:null,max:null,center:null,centerSpread:null};const min=Math.min(...values),max=Math.max(...values);const near=values.filter(v=>Math.abs(v)<1024);const center=near.length?near.reduce((a,b)=>a+b,0)/near.length:null;const spread=near.length?Math.sqrt(near.reduce((a,b)=>a+(b-center)**2,0)/near.length):null;return {count:values.length,min,max,center:center===null?null:Math.round(center),centerSpread:spread===null?null:Math.round(spread)}}
export function clockBpm(timestamps=[]){if(timestamps.length<25)return null;const diffs=[];for(let i=1;i<timestamps.length;i++){const d=timestamps[i]-timestamps[i-1];if(d>0&&d<500)diffs.push(d)}if(!diffs.length)return null;diffs.sort((a,b)=>a-b);const median=diffs[Math.floor(diffs.length/2)];return 60000/(median*24)}
export function classifyEncoder(values=[]){if(values.length<4)return 'Insufficient data';const set=new Set(values);if(Math.min(...values)>=0&&Math.max(...values)<=127&&set.size>16)return 'Absolute 0–127';if(set.size<=2)return 'Switch / button';const mostly=values.filter(v=>v===1||v===65||v===63||v===127).length/values.length;if(mostly>.7)return 'Likely relative encoder';return 'Unknown / mixed'}
export function messageRate(timestamps=[],windowMs=1000,now){if(!timestamps.length)return 0;const end=now??timestamps[timestamps.length-1],start=end-windowMs;return timestamps.filter(t=>t>=start).length/(windowMs/1000)}
export function reportSummary(state){return {device:state.device||'',started:state.started||null,durationMs:state.started?Date.now()-state.started:0,eventCount:state.events?.length||0,keys:[...(state.keys||[])].sort((a,b)=>a-b),channels:[...(state.channels||[])].sort((a,b)=>a-b),messageCounts:state.messageCounts||{},disconnects:state.disconnects||0,controls:state.controls||{},pitch:state.pitch||{}}}

export function velocityHistogram(values=[],bins=8){const h=Array(bins).fill(0);for(const v of values)h[Math.min(bins-1,Math.floor(Math.max(0,v-1)/(127/bins)))]++;return h}
export function detectChatter(events=[],thresholdMs=40){const last=new Map();let count=0;for(const e of events){if(e.kind!=='noteon'&&e.kind!=='noteoff')continue;const k=`${e.channel}:${e.a}`;if(e.kind==='noteoff'){last.set(k,{off:true,t:e.t});continue}const p=last.get(k);if(p&&p.off&&e.t-p.t<thresholdMs)count++;last.set(k,{off:false,t:e.t})}return count}
export function eventsToCsv(events=[]){return ['time_ms,channel,kind,label,data1,data2,value,hex',...events.map(e=>[e.t.toFixed(3),e.channel??'',e.kind,`"${e.label}"`,e.a,e.b,e.value,`"${e.hex}"`].join(','))].join('\n')}
export function interval(timestamps=[]){if(timestamps.length<3)return {mean:0,max:0,stdev:0};const d=[];for(let i=1;i<timestamps.length;i++)d.push(timestamps[i]-timestamps[i-1]);const m=d.reduce((a,b)=>a+b,0)/d.length;return {mean:m,max:Math.max(...d),stdev:Math.sqrt(d.reduce((a,b)=>a+(b-m)**2,0)/d.length)}}
