import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {FIXTURES} from '../tools/make-fixtures.mjs';
import {inputFromEvents} from './helpers/state-from-events.mjs';
import {buildTestResults} from '../midi-tests.js';
import {serializeCapture,parseCapture} from '../lib/capture.js';
import {evaluateChecklist} from '../lib/checklists.js';

const statuses=evs=>Object.fromEntries(buildTestResults(inputFromEvents(evs)).map(r=>[r.id,r.status]));
for(const [name,f] of Object.entries(FIXTURES)){
  const evs=f.build(),st=statuses(evs);
  for(const [id,want] of Object.entries(f.expect))assert.equal(st[id],want,name+': '+id+' expected '+want+' got '+st[id]);
  // capture round trip must not change any test status
  const back=parseCapture(serializeCapture(evs,{device:name}));assert.ok(!back.error,back.error);
  const st2=statuses(back.events.map(x=>({t:x.t,deviceId:x.deviceId,raw:x.bytes})));
  assert.deepEqual(st2,st,name+': statuses changed after save/load');
  // committed fixture file (generated by tools/make-fixtures.mjs) must still parse
  const file=new URL('./fixtures/'+name+'.capture.json',import.meta.url);
  if(existsSync(file)){const p=parseCapture(readFileSync(file,'utf8'));assert.ok(!p.error,name+' file: '+p.error);assert.equal(p.events.length,evs.length,name+' file out of date: rerun node tools/make-fixtures.mjs')}
}
// checklist on the good keyboard: all 61 keys seen
{const evs=FIXTURES['good-keyboard'].build(),inp=inputFromEvents(evs),tests=buildTestResults(inp);
 const r=evaluateChecklist('keyboard61',{keys:[...new Set(inp.events.filter(e=>e.kind==='noteon').map(e=>e.a))],expected:{low:36,high:96},velocityValues:inp.velocityValues,cc:inp.cc,pitchValues:[],sustainValues:inp.sustainValues,aftertouchCount:0,tests,manual:{},skipped:{}});
 const keys=r.items.find(i=>i.id==='keys');assert.equal(keys.status,'pass');}
{const evs=FIXTURES['good-keyboard'].build().filter(e=>!(e.raw[0]===0x90&&e.raw[1]===60)),inp=inputFromEvents(evs),tests=buildTestResults(inp);
 const r=evaluateChecklist('keyboard61',{keys:[...new Set(inp.events.filter(e=>e.kind==='noteon').map(e=>e.a))],expected:{low:36,high:96},velocityValues:inp.velocityValues,cc:inp.cc,pitchValues:[],sustainValues:inp.sustainValues,aftertouchCount:0,tests,manual:{},skipped:{}});
 const keys=r.items.find(i=>i.id==='keys');assert.equal(keys.status,'fail');assert.match(keys.detail,/C4|60/);assert.equal(r.verdict==='PASS',false);}
console.log('MIDItest fixtures tests: PASS');
